const fs = require("node:fs");
const path = require("node:path");

const { loadEntities, publicEntityRecords } = require("../../backend/lib/entities");
const { resolveCleanRouteAlias } = require("../build-pages");

const GENERATED_PAGE_BANNER = "<!-- Generated from site-src by tools/build-pages.js. Do not edit this file directly. -->";

function readJson(root, relativePath) {
  return JSON.parse(fs.readFileSync(path.join(root, relativePath), "utf8"));
}

function normalizeRelativePath(root, absolutePath) {
  return path.relative(root, absolutePath).split(path.sep).join("/");
}

function expectedGeneratedPagePaths(root) {
  const manifest = readJson(root, "site-src/page-manifest.json");
  if (!Array.isArray(manifest)) {
    throw new Error("site-src/page-manifest.json must contain an array.");
  }

  const expected = new Set();
  manifest.forEach((entry) => {
    if (!entry || typeof entry.output !== "string" || !entry.output) {
      throw new Error("Every page manifest entry must define an output path.");
    }

    expected.add(entry.output);
    const cleanRouteAlias = resolveCleanRouteAlias(entry);
    if (cleanRouteAlias) {
      expected.add(path.posix.join(cleanRouteAlias, "index.html"));
    }
  });

  const catalog = readJson(root, "data/shows.json");
  const entities = publicEntityRecords(loadEntities(root, catalog), catalog);
  entities.forEach((entity) => {
    expected.add(path.posix.join("creators", entity.id, "index.html"));
  });

  return expected;
}

function listGeneratedHtmlPaths(root) {
  const generated = new Set();

  function walk(currentPath) {
    fs.readdirSync(currentPath, { withFileTypes: true }).forEach((entry) => {
      if (entry.name === ".git" || entry.name === "node_modules") {
        return;
      }

      const absolutePath = path.join(currentPath, entry.name);
      if (entry.isDirectory()) {
        walk(absolutePath);
        return;
      }

      if (!entry.name.endsWith(".html")) {
        return;
      }

      if (fs.readFileSync(absolutePath, "utf8").includes(GENERATED_PAGE_BANNER)) {
        generated.add(normalizeRelativePath(root, absolutePath));
      }
    });
  }

  walk(root);
  return generated;
}

function validateGeneratedPages(root) {
  const expected = expectedGeneratedPagePaths(root);
  const actual = listGeneratedHtmlPaths(root);
  const missing = [...expected].filter((relativePath) => !actual.has(relativePath)).sort();
  const unexpected = [...actual].filter((relativePath) => !expected.has(relativePath)).sort();

  if (missing.length || unexpected.length) {
    const details = [
      missing.length ? `missing: ${missing.join(", ")}` : "",
      unexpected.length ? `unexpected: ${unexpected.join(", ")}` : "",
    ].filter(Boolean).join("; ");
    throw new Error(`Generated HTML output does not match the page manifest/catalog (${details}).`);
  }

  return { expected, actual };
}

module.exports = {
  GENERATED_PAGE_BANNER,
  expectedGeneratedPagePaths,
  listGeneratedHtmlPaths,
  validateGeneratedPages,
};
