// Generated from tools/build-pages.js. Do not edit this file directly.
import { initializeApp } from "./shared/app/app.js?v=028e60e0ca";

initializeApp().catch((error) => {
  console.error("Failed to initialize the Echo Archives app.", error);
});
