// Generated from tools/build-pages.js. Do not edit this file directly.
const CACHE_VERSION = "c930b59d5f";
const HTML_CACHE = `echo-archives-html-${CACHE_VERSION}`;
const ASSET_CACHE = `echo-archives-assets-${CACHE_VERSION}`;
const PRECACHE_URLS = [
  "/",
  "/404.html",
  "/500.html",
  "/about",
  "/apple-touch-icon.png",
  "/collections",
  "/cookies",
  "/copyright",
  "/creator-standards",
  "/data/collections.json",
  "/data/search-index.json",
  "/data/shows.json",
  "/detail.css?v=c77b45dfe2",
  "/favicon.ico",
  "/for-creators",
  "/help-center",
  "/home.css?v=86d7f51418",
  "/icon-192.png",
  "/icon-512.png",
  "/offline.html",
  "/og-image.png",
  "/privacy",
  "/script.js?v=37f51f2e4a",
  "/shared/archive-record.js?v=d3d37891f4",
  "/shared/archive-search.js?v=f9204f6b58",
  "/site.webmanifest",
  "/style.css?v=37191a0966",
  "/submit",
  "/supporters",
  "/terms"
];
const OFFLINE_FALLBACK_URL = "/offline.html";

self.addEventListener("install", (event) => {
  event.waitUntil(
    caches.open(ASSET_CACHE).then((cache) => cache.addAll(PRECACHE_URLS)).then(() => self.skipWaiting()),
  );
});

self.addEventListener("activate", (event) => {
  event.waitUntil(
    caches
      .keys()
      .then((keys) => Promise.all(keys.filter((key) => key.startsWith("echo-archives-") && key !== HTML_CACHE && key !== ASSET_CACHE).map((key) => caches.delete(key))))
      .then(() => self.clients.claim()),
  );
});

self.addEventListener("fetch", (event) => {
  const { request } = event;
  if (request.method !== "GET") {
    return;
  }

  const url = new URL(request.url);
  if (url.origin !== self.location.origin || url.pathname.startsWith("/api/")) {
    return;
  }

  if (request.mode === "navigate") {
    event.respondWith(handleNavigationRequest(request));
    return;
  }

  event.respondWith(handleAssetRequest(request));
});

async function handleNavigationRequest(request) {
  const cache = await caches.open(HTML_CACHE);

  try {
    const response = await fetch(request);
    if (response && response.ok) {
      void cache.put(request, response.clone());
    }
    return response;
  } catch (_error) {
    const cachedResponse = await cache.match(request);
    if (cachedResponse) {
      return cachedResponse;
    }

    const precachedFallback = await caches.match(request.url);
    if (precachedFallback) {
      return precachedFallback;
    }

    return caches.match(OFFLINE_FALLBACK_URL);
  }
}

async function handleAssetRequest(request) {
  const cachedResponse = await caches.match(request);
  if (cachedResponse) {
    void refreshAssetCache(request);
    return cachedResponse;
  }

  const response = await fetch(request);
  if (response && response.ok) {
    const cache = await caches.open(ASSET_CACHE);
    void cache.put(request, response.clone());
  }

  return response;
}

async function refreshAssetCache(request) {
  try {
    const response = await fetch(request);
    if (!response || !response.ok) {
      return;
    }

    const cache = await caches.open(ASSET_CACHE);
    await cache.put(request, response.clone());
  } catch (_error) {
    // Keep the cached asset when refresh fails.
  }
}
