// Generated from tools/build-pages.js. Do not edit this file directly.
const CACHE_VERSION = "6049fe6f68";
const HTML_CACHE = `echo-archives-html-${CACHE_VERSION}`;
const ASSET_CACHE = `echo-archives-assets-${CACHE_VERSION}`;
const PRECACHE_URLS = [
  "/apple-touch-icon.png",
  "/echo-wordmark-nosub1.svg",
  "/echo-wordmark-sub1.svg",
  "/echo-wordmark1.png",
  "/favicon.ico",
  "/icon-192.png",
  "/icon-512.png",
  "/info.css?v=236c1db4ca",
  "/offline.html",
  "/public-heroes.css?v=fe0218257a",
  "/script.js?v=b2014df27b",
  "/shared/app/app.js?v=b61d69a8fc",
  "/shared/app/constants.js",
  "/shared/app/home-config.js",
  "/shared/app/images.js",
  "/shared/app/mobile-nav.js",
  "/shared/app/service-worker.js",
  "/shared/app/toast.js",
  "/shared/app/utils.js",
  "/shared/app/viewport-metrics.js",
  "/shared/archive-record.js?v=ad773d906f",
  "/shared/archive-search.js?v=cc69d7d5dc",
  "/site.webmanifest",
  "/style.css?v=4b2bfbc0f8"
];
const OFFLINE_FALLBACK_URL = "/offline.html";

self.addEventListener("install", (event) => {
  event.waitUntil(
    caches.open(ASSET_CACHE).then((cache) => cache.addAll(PRECACHE_URLS)).then(() => self.skipWaiting()),
  );
});

self.addEventListener("activate", (event) => {
  event.waitUntil(
    caches
      .keys()
      .then((keys) => Promise.all(keys.filter((key) => key.startsWith("echo-archives-") && key !== HTML_CACHE && key !== ASSET_CACHE).map((key) => caches.delete(key))))
      .then(async () => {
        const clients = await self.clients.matchAll({ type: "window", includeUncontrolled: true });
        await Promise.all(clients.map((client) => cacheVisitedPage(client.url)));
        await self.clients.claim();
      }),
  );
});

self.addEventListener("fetch", (event) => {
  const { request } = event;
  if (request.method !== "GET") {
    return;
  }

  const url = new URL(request.url);
  if (url.origin !== self.location.origin || url.pathname.startsWith("/api/")) {
    return;
  }

  if (request.mode === "navigate") {
    event.respondWith(handleNavigationRequest(request));
    return;
  }

  event.respondWith(handleAssetRequest(request));
});

self.addEventListener("message", (event) => {
  if (event.data?.type !== "CACHE_VISITED_RESOURCES") {
    return;
  }

  const responsePort = event.ports?.[0];
  event.waitUntil(
    cacheVisitedResources(event.data.urls)
      .then((cached) => responsePort?.postMessage({ cached }))
      .catch(() => responsePort?.postMessage({ cached: 0 })),
  );
});

async function handleNavigationRequest(request) {
  const cache = await caches.open(HTML_CACHE);

  try {
    const response = await fetch(request);
    if (response && response.ok) {
      void cache.put(request, response.clone());
    }
    return response;
  } catch (_error) {
    const cachedResponse = await cache.match(request);
    if (cachedResponse) {
      return cachedResponse;
    }

    const precachedFallback = await caches.match(request.url);
    if (precachedFallback) {
      return precachedFallback;
    }

    return caches.match(OFFLINE_FALLBACK_URL);
  }
}

async function cacheVisitedPage(url) {
  try {
    const response = await fetch(url, { credentials: "same-origin" });
    if (!response || !response.ok) {
      return;
    }

    const cache = await caches.open(HTML_CACHE);
    await cache.put(url, response.clone());
  } catch (_error) {
    // A visited page can still be cached by its next successful navigation.
  }
}

async function cacheVisitedResources(urls) {
  const uniqueUrls = [...new Set(Array.isArray(urls) ? urls : [])]
    .map((value) => {
      try {
        return new URL(value, self.location.origin);
      } catch (_error) {
        return null;
      }
    })
    .filter((url) => url && url.origin === self.location.origin && !url.pathname.startsWith("/api/"));
  let cached = 0;

  await Promise.all(uniqueUrls.map(async (url) => {
    try {
      const response = await fetch(url.href, { credentials: "same-origin" });
      if (!response || !response.ok) {
        return;
      }
      const destinationCache = isHtmlUrl(url) ? HTML_CACHE : ASSET_CACHE;
      const cache = await caches.open(destinationCache);
      await cache.put(url.href, response.clone());
      cached += 1;
    } catch (_error) {
      // Individual optional assets must not prevent the visited page from becoming offline-ready.
    }
  }));
  return cached;
}

function isHtmlUrl(url) {
  return url.pathname === "/" || url.pathname.endsWith("/") || url.pathname.endsWith(".html") || !/\.[a-z0-9]+$/i.test(url.pathname);
}

async function handleAssetRequest(request) {
  const url = new URL(request.url);
  if (shouldUseNetworkFirstAssetStrategy(request, url)) {
    return handleNetworkFirstAssetRequest(request);
  }

  const cachedResponse = await caches.match(request);
  if (cachedResponse) {
    void refreshAssetCache(request);
    return cachedResponse;
  }

  const response = await fetch(request);
  if (response && response.ok) {
    const cache = await caches.open(ASSET_CACHE);
    void cache.put(request, response.clone());
  }

  return response;
}

function shouldUseNetworkFirstAssetStrategy(request, url) {
  return request.destination === "script" || request.destination === "style" || /\.(?:js|css)$/i.test(url.pathname);
}

async function handleNetworkFirstAssetRequest(request) {
  try {
    const response = await fetch(request);
    if (response && response.ok) {
      const cache = await caches.open(ASSET_CACHE);
      void cache.put(request, response.clone());
    }

    return response;
  } catch (_error) {
    const cachedResponse = await caches.match(request);
    if (cachedResponse) {
      return cachedResponse;
    }

    throw _error;
  }
}

async function refreshAssetCache(request) {
  const cachedResponse = await caches.match(request);
  try {
    const response = await fetch(request);
    if (!response || !response.ok) {
      return;
    }

    const cache = await caches.open(ASSET_CACHE);
    await cache.put(request, response.clone());
  } catch (_error) {
    // Keep the cached asset when refresh fails.
  }
}
