// Generated from tools/build-pages.js. Do not edit this file directly.
const CACHE_VERSION = "40c2af5176";
const HTML_CACHE = `echo-archives-html-${CACHE_VERSION}`;
const ASSET_CACHE = `echo-archives-assets-${CACHE_VERSION}`;
const PRECACHE_URLS = [
  "/",
  "/about",
  "/apple-touch-icon.png",
  "/collections",
  "/cookies",
  "/copyright",
  "/creator-standards",
  "/data/collections.json?v=9afac6e32d",
  "/data/search-index.json?v=882e8181c9",
  "/data/shows.json?v=070f2cb66e",
  "/detail.css?v=405b73ebef",
  "/favicon.ico",
  "/for-creators",
  "/help-center",
  "/home.css?v=935655c33b",
  "/icon-192.png",
  "/icon-512.png",
  "/offline.html",
  "/og-image.png",
  "/privacy",
  "/script.js?v=516906fc9e",
  "/shared/app/app.js?v=40eb5d3e42",
  "/shared/app/chat-loader.js",
  "/shared/app/chat-open.js",
  "/shared/app/chat.js",
  "/shared/app/chat/context.js",
  "/shared/app/chat/messages.js",
  "/shared/app/chat/persistence.js",
  "/shared/app/chat/ui.js",
  "/shared/app/collection-carousel-centering.js",
  "/shared/app/collection-carousel-focus.js",
  "/shared/app/collection-carousel.js",
  "/shared/app/community.js",
  "/shared/app/community/api.js",
  "/shared/app/community/badges.js",
  "/shared/app/community/detail-motion.js",
  "/shared/app/community/detail-widget.js",
  "/shared/app/community/formatters.js",
  "/shared/app/community/turnstile.js",
  "/shared/app/constants.js",
  "/shared/app/data.js",
  "/shared/app/home-config.js",
  "/shared/app/home-preview.js",
  "/shared/app/home-preview/helpers.js",
  "/shared/app/home-preview/hit-testing.js",
  "/shared/app/home-preview/position.js",
  "/shared/app/images.js",
  "/shared/app/maintainer-import/format.js",
  "/shared/app/maintainer-import/page-helpers.js",
  "/shared/app/maintainer-import/render.js",
  "/shared/app/maintainer/api.js",
  "/shared/app/maintainer/format.js",
  "/shared/app/maintainer/page-helpers.js",
  "/shared/app/maintainer/render.js",
  "/shared/app/mobile-nav.js",
  "/shared/app/pages/about.js",
  "/shared/app/pages/accordion.js",
  "/shared/app/pages/collection.js",
  "/shared/app/pages/collections-grid-motion.js",
  "/shared/app/pages/collections-intents.js",
  "/shared/app/pages/collections-motion.js",
  "/shared/app/pages/collections.js",
  "/shared/app/pages/creators.js",
  "/shared/app/pages/help-center.js",
  "/shared/app/pages/home.js",
  "/shared/app/pages/home/collections.js",
  "/shared/app/pages/home/data-load.js",
  "/shared/app/pages/home/elements.js",
  "/shared/app/pages/home/filter-active-state.js",
  "/shared/app/pages/home/filter-controls.js",
  "/shared/app/pages/home/filter-dropdown.js",
  "/shared/app/pages/home/filter-menu.js",
  "/shared/app/pages/home/filter-motion.js",
  "/shared/app/pages/home/filter-state.js",
  "/shared/app/pages/home/filter-surfaces.js",
  "/shared/app/pages/home/filter-utils.js",
  "/shared/app/pages/home/filters.js",
  "/shared/app/pages/home/grid-motion.js",
  "/shared/app/pages/home/layout.js",
  "/shared/app/pages/home/loading.js",
  "/shared/app/pages/home/most-popular.js",
  "/shared/app/pages/home/prerender.js",
  "/shared/app/pages/home/recently-added.js",
  "/shared/app/pages/home/results-motion.js",
  "/shared/app/pages/home/results.js",
  "/shared/app/pages/home/search-cache.js",
  "/shared/app/pages/home/state.js",
  "/shared/app/pages/home/sticky-search.js",
  "/shared/app/pages/home/url-state.js",
  "/shared/app/pages/maintainer-imports.js",
  "/shared/app/pages/maintainer.js",
  "/shared/app/pages/show.js",
  "/shared/app/pages/submit.js",
  "/shared/app/pages/submit/click-handlers.js",
  "/shared/app/pages/submit/draft.js",
  "/shared/app/pages/submit/elements.js",
  "/shared/app/pages/submit/ui.js",
  "/shared/app/render-cards.js",
  "/shared/app/render-cards/badges.js",
  "/shared/app/render-cards/popular.js",
  "/shared/app/render-cards/preview.js",
  "/shared/app/render-cards/scores.js",
  "/shared/app/render-cards/shared.js",
  "/shared/app/render-collections.js",
  "/shared/app/render-show.js",
  "/shared/app/render-show/facts.js",
  "/shared/app/render-show/hero.js",
  "/shared/app/render-show/relationships.js",
  "/shared/app/render-show/sections.js",
  "/shared/app/render-show/utils.js",
  "/shared/app/route-error.js",
  "/shared/app/scroll-restoration.js",
  "/shared/app/service-worker.js",
  "/shared/app/share.js",
  "/shared/app/structured-data.js",
  "/shared/app/submit/api.js",
  "/shared/app/submit/config.js",
  "/shared/app/submit/config/mode-config.js",
  "/shared/app/submit/config/modes/correction.js",
  "/shared/app/submit/config/modes/creator-verification.js",
  "/shared/app/submit/config/modes/listener-review.js",
  "/shared/app/submit/config/modes/show.js",
  "/shared/app/submit/config/options.js",
  "/shared/app/submit/render.js",
  "/shared/app/submit/render/base-fields.js",
  "/shared/app/submit/render/choice-fields.js",
  "/shared/app/submit/render/link-fields.js",
  "/shared/app/submit/render/mode-cards.js",
  "/shared/app/submit/render/modes/correction.js",
  "/shared/app/submit/render/modes/creator-verification.js",
  "/shared/app/submit/render/modes/listener-review.js",
  "/shared/app/submit/render/modes/show.js",
  "/shared/app/submit/render/rail.js",
  "/shared/app/submit/search.js",
  "/shared/app/submit/state.js",
  "/shared/app/submit/utils.js",
  "/shared/app/submit/validation.js",
  "/shared/app/toast.js",
  "/shared/app/urls.js",
  "/shared/app/utils.js",
  "/shared/archive-record.js?v=cd1ad0c974",
  "/shared/archive-search.js?v=f9204f6b58",
  "/site.webmanifest",
  "/style.css?v=d2a12bfb7d",
  "/submit",
  "/supporters",
  "/terms"
];
const OFFLINE_FALLBACK_URL = "/offline.html";

self.addEventListener("install", (event) => {
  event.waitUntil(
    caches.open(ASSET_CACHE).then((cache) => cache.addAll(PRECACHE_URLS)).then(() => self.skipWaiting()),
  );
});

self.addEventListener("activate", (event) => {
  event.waitUntil(
    caches
      .keys()
      .then((keys) => Promise.all(keys.filter((key) => key.startsWith("echo-archives-") && key !== HTML_CACHE && key !== ASSET_CACHE).map((key) => caches.delete(key))))
      .then(() => self.clients.claim()),
  );
});

self.addEventListener("fetch", (event) => {
  const { request } = event;
  if (request.method !== "GET") {
    return;
  }

  const url = new URL(request.url);
  if (url.origin !== self.location.origin || url.pathname.startsWith("/api/")) {
    return;
  }

  if (request.mode === "navigate") {
    event.respondWith(handleNavigationRequest(request));
    return;
  }

  event.respondWith(handleAssetRequest(request));
});

async function handleNavigationRequest(request) {
  const cache = await caches.open(HTML_CACHE);

  try {
    const response = await fetch(request);
    if (response && response.ok) {
      void cache.put(request, response.clone());
    }
    return response;
  } catch (_error) {
    const cachedResponse = await cache.match(request);
    if (cachedResponse) {
      return cachedResponse;
    }

    const precachedFallback = await caches.match(request.url);
    if (precachedFallback) {
      return precachedFallback;
    }

    return caches.match(OFFLINE_FALLBACK_URL);
  }
}

async function handleAssetRequest(request) {
  const url = new URL(request.url);
  if (shouldUseNetworkFirstAssetStrategy(request, url)) {
    return handleNetworkFirstAssetRequest(request);
  }

  const cachedResponse = await caches.match(request);
  if (cachedResponse) {
    void refreshAssetCache(request);
    return cachedResponse;
  }

  const response = await fetch(request);
  if (response && response.ok) {
    const cache = await caches.open(ASSET_CACHE);
    void cache.put(request, response.clone());
  }

  return response;
}

function shouldUseNetworkFirstAssetStrategy(request, url) {
  return request.destination === "script" || request.destination === "style" || /\.(?:js|css)$/i.test(url.pathname);
}

async function handleNetworkFirstAssetRequest(request) {
  try {
    const response = await fetch(request);
    if (response && response.ok) {
      const cache = await caches.open(ASSET_CACHE);
      void cache.put(request, response.clone());
    }

    return response;
  } catch (_error) {
    const cachedResponse = await caches.match(request);
    if (cachedResponse) {
      return cachedResponse;
    }

    throw _error;
  }
}

async function refreshAssetCache(request) {
  const cachedResponse = await caches.match(request);
  try {
    const response = await fetch(request);
    if (!response || !response.ok) {
      return;
    }

    const cache = await caches.open(ASSET_CACHE);
    await cache.put(request, response.clone());
  } catch (_error) {
    // Keep the cached asset when refresh fails.
  }
}
