const crypto = require("node:crypto");
const fs = require("node:fs");
const path = require("node:path");
const { pathToFileURL } = require("node:url");

const { buildSitemapXml } = require("../backend/lib/sitemap");
const { renderHomePagePrerender } = require("./lib/home-page-prerender");

const ROOT = path.resolve(__dirname, "..");
const SITE_SRC = path.join(ROOT, "site-src");
const PARTIALS_DIR = path.join(SITE_SRC, "partials");
const PAGES_DIR = path.join(SITE_SRC, "pages");
const MANIFEST_PATH = path.join(SITE_SRC, "page-manifest.json");
const GENERATED_PAGE_BANNER = "<!-- Generated from site-src by tools/build-pages.js. Do not edit this file directly. -->";
const GENERATED_JS_BANNER = "// Generated from tools/build-pages.js. Do not edit this file directly.";
const GENERATED_CSS_BANNER = "/* Generated from tools/build-pages.js. Do not edit this file directly. */";
const DEFAULT_PLAUSIBLE_SCRIPT_SRC = "https://plausible.io/js/script.js";
const DEFAULT_SITE_URL = "https://echo.continental-hub.com";
const DEFAULT_SOCIAL_IMAGE_ALT = "The Echo Archives social preview";
const NOINDEX_ALIAS_PATHS = new Set(["show", "collection"]);

const ENTRY_ASSETS = {
  "script.js": ({ appVersion }) => [
    GENERATED_JS_BANNER,
    `import { initializeApp } from "./shared/app/app.js?v=${appVersion}";`,
    "",
    "initializeApp().catch((error) => {",
    '  console.error("Failed to initialize the Echo Archives app.", error);',
    "});",
    "",
  ].join("\n"),
  "style.css": () => renderCssBundle([
    "shared/styles/base/variables.css",
    "shared/styles/base/global.css",
    "shared/styles/base/header-footer.css",
    "shared/styles/base/chat.css",
  ]),
  "home.css": () => renderCssBundle([
    "shared/styles/home/hero.css",
    "shared/styles/home/filters.css",
    "shared/styles/home/cards.css",
    "shared/styles/home/submit.css",
    "shared/styles/home/maintainer.css",
    "shared/styles/home/collections.css",
    "shared/styles/home/creators.css",
    "shared/styles/home/responsive.css",
  ]),
  "detail.css": () => renderCssBundle([
    "shared/styles/show/hero.css",
    "shared/styles/show/sections.css",
    "shared/styles/show/facts-rail.css",
    "shared/styles/show/community.css",
    "shared/styles/show/responsive.css",
  ]),
};

function readFile(filePath) {
  return fs.readFileSync(filePath, "utf8");
}

function writeFile(filePath, contents) {
  fs.mkdirSync(path.dirname(filePath), { recursive: true });
  fs.writeFileSync(filePath, contents);
}

function rewriteCssAssetUrls(contents, sourcePath) {
  return contents.replace(/url\(\s*(["']?)([^"')]+)\1\s*\)/gi, (match, quote, rawValue) => {
    const value = String(rawValue || "").trim();
    if (!value || /^(?:[a-z]+:|\/\/|\/|#)/i.test(value)) {
      return match;
    }

    const suffixIndex = value.search(/[?#]/);
    const pathname = suffixIndex >= 0 ? value.slice(0, suffixIndex) : value;
    const suffix = suffixIndex >= 0 ? value.slice(suffixIndex) : "";
    const resolvedPath = path.resolve(path.dirname(sourcePath), pathname);
    const relativePath = path.relative(ROOT, resolvedPath);
    if (relativePath.startsWith("..") || path.isAbsolute(relativePath)) {
      throw new Error(`CSS asset escapes the public root: ${value} in ${path.relative(ROOT, sourcePath)}`);
    }

    const publicUrl = `/${relativePath.split(path.sep).join("/")}${suffix}`;
    const renderedQuote = quote || '"';
    return `url(${renderedQuote}${publicUrl}${renderedQuote})`;
  });
}

function flattenCssFile(filePath, ancestry = []) {
  const normalizedPath = path.resolve(filePath);
  if (ancestry.includes(normalizedPath)) {
    const cycle = [...ancestry, normalizedPath].map((entry) => path.relative(ROOT, entry)).join(" -> ");
    throw new Error(`Circular CSS import detected: ${cycle}`);
  }

  const nextAncestry = [...ancestry, normalizedPath];
  const contents = readFile(normalizedPath);
  const flattened = contents.replace(
    /@import\s+(?:url\(\s*)?["']([^"']+)["']\s*\)?\s*;/gi,
    (_match, importValue) => {
      const relativeImport = stripQuery(importValue);
      if (/^(?:[a-z]+:|\/\/|\/)/i.test(relativeImport)) {
        throw new Error(`External or root CSS import cannot be flattened: ${importValue}`);
      }

      const importedPath = path.resolve(path.dirname(normalizedPath), relativeImport);
      return flattenCssFile(importedPath, nextAncestry);
    },
  );

  return [
    `/* Source: ${path.relative(ROOT, normalizedPath).split(path.sep).join("/")} */`,
    rewriteCssAssetUrls(flattened, normalizedPath).trim(),
  ].join("\n");
}

function renderCssBundle(relativePaths) {
  const contents = `${[
    GENERATED_CSS_BANNER,
    ...relativePaths.map((relativePath) => flattenCssFile(path.join(ROOT, relativePath))),
  ]
    .join("\n\n")
    .replace(/[ \t]+$/gm, "")
    .trimEnd()}\n`;

  if (/@import\b/i.test(contents)) {
    throw new Error("Generated CSS bundle still contains an @import rule.");
  }

  return contents;
}

function hashBuffer(buffer) {
  return crypto.createHash("sha1").update(buffer).digest("hex").slice(0, 10);
}

function listFilesDeep(startPath) {
  const results = [];

  if (!fs.existsSync(startPath)) {
    return results;
  }

  function walk(currentPath) {
    fs.readdirSync(currentPath, { withFileTypes: true }).forEach((entry) => {
      const absolutePath = path.join(currentPath, entry.name);
      if (entry.isDirectory()) {
        walk(absolutePath);
        return;
      }

      results.push(absolutePath);
    });
  }

  walk(startPath);
  return results.sort((left, right) => left.localeCompare(right));
}

function hashFile(relativePath) {
  return hashBuffer(fs.readFileSync(path.join(ROOT, relativePath)));
}

function hashTree(relativePath) {
  const files = listFilesDeep(path.join(ROOT, relativePath));
  const hash = crypto.createHash("sha1");

  files.forEach((filePath) => {
    hash.update(path.relative(ROOT, filePath));
    hash.update(fs.readFileSync(filePath));
  });

  return hash.digest("hex").slice(0, 10);
}

function stripQuery(value = "") {
  return String(value || "").split("?", 1)[0];
}

function withVersion(relativePath, version) {
  return `${relativePath}?v=${version}`;
}

function getVersionedSearchIndexUrl(version) {
  return `/${withVersion("data/search-index.json", version)}`;
}

function getVersionedDataUrl(fileName, version) {
  return `/${withVersion(`data/${fileName}`, version)}`;
}

function renderTemplate(template, replacements) {
  return template.replace(/\{\{([a-zA-Z0-9]+)\}\}/g, (_match, key) => replacements[key] ?? "");
}

function escapeAttribute(value = "") {
  return String(value)
    .replace(/&/g, "&amp;")
    .replace(/"/g, "&quot;");
}

function escapeHtml(value = "") {
  return String(value)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;");
}

function escapeRegExp(value = "") {
  return String(value).replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

function parseBoolean(value, fallback = false) {
  if (value === undefined) {
    return fallback;
  }

  return /^(1|true|yes|on)$/i.test(String(value).trim());
}

function renderStylesheets(extraStylesheets = [], versions = {}) {
  return [
    `<link rel="stylesheet" href="/style.css?v=${versions.style}" />`,
    `<link rel="stylesheet" href="/home.css?v=${versions.home}" />`,
    ...extraStylesheets.map((href) => {
      const basePath = stripQuery(href);
      const version = versions.extra.get(basePath) || hashFile(basePath);
      return `<link rel="stylesheet" href="/${withVersion(basePath, version)}" />`;
    }),
  ].join("\n");
}

function renderRobotsMeta(entry) {
  return entry.noIndex ? '<meta name="robots" content="noindex, nofollow" />' : "";
}

function renderAnalyticsScript(entry) {
  const plausibleDomain = String(process.env.PLAUSIBLE_DOMAIN || "").trim();
  if (!plausibleDomain || entry.includeAnalytics === false) {
    return "";
  }

  const plausibleScriptSrc = String(process.env.PLAUSIBLE_SCRIPT_SRC || DEFAULT_PLAUSIBLE_SCRIPT_SRC).trim();
  if (!plausibleScriptSrc) {
    return "";
  }

  return `<script defer data-domain="${escapeAttribute(plausibleDomain)}" src="${escapeAttribute(plausibleScriptSrc)}"></script>`;
}

function renderNavLinks(activeNav) {
  const navItems = [
    { id: "browse", label: "Browse", detail: "All shows and archive filters", href: "/" },
    { id: "collections", label: "Collections", detail: "Curated listening paths", href: "/collections" },
    { id: "about", label: "About", detail: "What the archive is building", href: "/about" },
    { id: "submit", label: "Submit", detail: "Add shows or send corrections", href: "/submit" },
    { id: "for-creators", label: "For creators", detail: "Verification and standards", href: "/for-creators" },
  ];

  return navItems
    .map((item) => {
      const activeClass = item.id === activeNav ? ' class="is-active"' : "";
      return `<a${activeClass} href="${item.href}"><span class="site-nav-link-body"><span class="site-nav-link-label">${item.label}</span><span class="site-nav-link-detail">${item.detail}</span></span><span class="site-nav-link-arrow" aria-hidden="true"></span></a>`;
    })
    .join("\n    ");
}

function resolveMainContentTarget(entry) {
  return entry.source === "show.html" ? "showRoot" : "main-content";
}

function renderSkipLink(targetId) {
  return `<a class="skip-link" href="#${escapeAttribute(targetId)}">Skip to main content</a>`;
}

function ensureMainContentTarget(pageBody, targetId) {
  if (!targetId) {
    return pageBody;
  }

  const existingTargetPattern = new RegExp(`<main\\b([^>]*\\bid="${escapeRegExp(targetId)}"[^>]*)>`, "i");
  if (existingTargetPattern.test(pageBody)) {
    return pageBody.replace(existingTargetPattern, (match, attributes) => {
      if (/\btabindex=/.test(attributes)) {
        return match;
      }

      return `<main${attributes} tabindex="-1">`;
    });
  }

  return pageBody.replace(/<main\b(?![^>]*\bid=)/i, `<main id="${escapeAttribute(targetId)}" tabindex="-1"`);
}

function replaceElementTextById(html, id, value) {
  const pattern = new RegExp(`(<([a-z][a-z0-9-]*)\\b[^>]*\\bid="${escapeRegExp(id)}"[^>]*>)[\\s\\S]*?(<\\/\\2>)`, "i");
  return html.replace(pattern, `$1${escapeHtml(value)}$3`);
}

function formatLongDate(value) {
  const match = /^(\d{4})-(\d{2})-(\d{2})$/.exec(String(value || "").trim());
  if (!match) {
    return value ? "Date needs review" : "Unknown";
  }

  const [, year, month, day] = match;
  const date = new Date(Number(year), Number(month) - 1, Number(day));
  if (
    date.getFullYear() !== Number(year) ||
    date.getMonth() !== Number(month) - 1 ||
    date.getDate() !== Number(day)
  ) {
    return "Date needs review";
  }

  return new Intl.DateTimeFormat("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  }).format(date);
}

function getMetadataCoverageContext(stats) {
  const showCount = Number(stats?.showCount) || 0;
  const metadataCheckedCount = Number(stats?.metadataCheckedCount) || 0;
  if (showCount === 0) {
    return "No published records yet.";
  }
  if (metadataCheckedCount === showCount) {
    return "All published records currently have sourced metadata.";
  }
  return `${metadataCheckedCount.toLocaleString("en-US")} of ${showCount.toLocaleString("en-US")} published records currently have sourced metadata.`;
}

function prerenderArchiveStats(pageBody, entry, archiveStats) {
  const stats = archiveStats && typeof archiveStats === "object" ? archiveStats : {};
  if (!Number.isFinite(Number(stats.showCount))) {
    return pageBody;
  }
  const valuesByOutput = {
    "about.html": {
      aboutShowCount: Number(stats.showCount) || 0,
      aboutReviewCount: Number(stats.fullReviewCount) || 0,
      aboutCollectionCount: Number(stats.collectionCount) || 0,
      aboutLastUpdated: formatLongDate(stats.latestUpdatedAt),
    },
    "for-creators.html": {
      creatorsCreatorCount: Number(stats.creatorCount) || 0,
      creatorsShowCount: Number(stats.showCount) || 0,
      creatorsMetadataCount: Number(stats.metadataCheckedCount) || 0,
      creatorsMetadataContext: getMetadataCoverageContext(stats),
      creatorsReviewCount: Number(stats.fullReviewCount) || 0,
      creatorsLastUpdated: formatLongDate(stats.latestUpdatedAt),
    },
  };
  const values = valuesByOutput[entry.output];
  if (!values) {
    return pageBody;
  }

  return Object.entries(values).reduce(
    (rendered, [id, value]) => replaceElementTextById(rendered, id, value),
    pageBody,
  );
}

function renderPageBody(entry, homeConfig, archiveStats) {
  let pageBody = ensureMainContentTarget(readFile(path.join(PAGES_DIR, entry.source)).trim(), resolveMainContentTarget(entry));

  if (entry.output === "index.html") {
    pageBody = renderHomePagePrerender(pageBody, {
      rootDir: ROOT,
      homeMostPopularIds: homeConfig.homeMostPopularIds,
      homeFavoriteRouteIds: homeConfig.homeFavoriteRouteIds,
    });
  }

  return prerenderArchiveStats(pageBody, entry, archiveStats);
}

function buildEntryAssets() {
  const nestedVersions = {
    appVersion: hashTree("shared/app"),
    baseVersion: hashTree("shared/styles/base"),
    homeVersion: hashTree("shared/styles/home"),
    submitVersion: hashTree("shared/styles/home/submit"),
    collectionsVersion: hashTree("shared/styles/home/collections"),
    creatorsVersion: hashTree("shared/styles/home/creators"),
    showVersion: hashTree("shared/styles/show"),
  };

  Object.entries(ENTRY_ASSETS).forEach(([fileName, render]) => {
    writeFile(path.join(ROOT, fileName), render(nestedVersions));
  });
}

function serializeStructuredData(value) {
  return JSON.stringify(value)
    .replace(/</g, "\\u003c")
    .replace(/\u2028/g, "\\u2028")
    .replace(/\u2029/g, "\\u2029");
}

function renderStructuredData(value) {
  if (!value) {
    return "";
  }
  return `<script id="pageStructuredData" type="application/ld+json">${serializeStructuredData(value)}</script>`;
}

function buildCollectionsStructuredData({ siteUrl, entry, collections }) {
  return {
    "@context": "https://schema.org",
    "@type": "CollectionPage",
    name: entry.title,
    description: entry.description,
    url: entry.canonicalUrl,
    mainEntity: {
      "@type": "ItemList",
      numberOfItems: collections.length,
      itemListElement: collections.map((collection, index) => ({
        "@type": "ListItem",
        position: index + 1,
        name: collection.title,
        url: new URL(`/collection?id=${encodeURIComponent(collection.id)}`, `${siteUrl}/`).toString(),
      })),
    },
  };
}

function buildPageStructuredData({ siteUrl, entry, collections }) {
  if (entry.output === "index.html") {
    return {
      "@context": "https://schema.org",
      "@type": "WebSite",
      name: "The Echo Archives",
      url: new URL("/", `${siteUrl}/`).toString(),
      description: entry.description,
      potentialAction: {
        "@type": "SearchAction",
        target: {
          "@type": "EntryPoint",
          urlTemplate: `${new URL("/", `${siteUrl}/`).toString()}?q={search_term_string}#archive`,
        },
        "query-input": "required name=search_term_string",
      },
    };
  }

  if (entry.output === "collections.html") {
    return buildCollectionsStructuredData({ siteUrl, entry, collections });
  }

  return null;
}

function renderPage(entry, partials, versions, homeConfig, seoContext) {
  const homeCardHoverExpandEnabled = parseBoolean(process.env.HOME_CARD_HOVER_EXPAND_ENABLED, false);
  const socialImageUrl = new URL("/og-image.png", `${seoContext.siteUrl}/`).toString();
  const structuredData = buildPageStructuredData({
    siteUrl: seoContext.siteUrl,
    entry,
    collections: seoContext.collections,
  });
  const headMarkup = renderTemplate(partials.head, {
    title: entry.title,
    description: entry.description,
    canonicalUrl: entry.canonicalUrl,
    socialImageUrl,
    socialImageAlt: DEFAULT_SOCIAL_IMAGE_ALT,
    robotsMeta: renderRobotsMeta(entry),
    analyticsScript: renderAnalyticsScript(entry),
    stylesheets: renderStylesheets(entry.extraStylesheets, versions),
  });
  const headerMarkup = renderTemplate(partials.header, {
    navLinks: renderNavLinks(entry.activeNav),
  });
  const mainContentTarget = resolveMainContentTarget(entry);
  const pageBody = renderPageBody(entry, homeConfig, seoContext.archiveStats);
  const bodySections = [
    renderSkipLink(mainContentTarget),
    headerMarkup,
    pageBody,
    entry.includeFloatingControls ? partials.floatingControls : "",
    partials.footer,
    `  <script src="/shared/archive-record.js?v=${versions.archiveRecord}"></script>`,
    `  <script src="/shared/archive-search.js?v=${versions.archiveSearch}"></script>`,
    `  <script type="module" src="/script.js?v=${versions.script}"></script>`,
  ]
    .filter(Boolean)
    .join("\n\n");

  return [
    "<!DOCTYPE html>",
    GENERATED_PAGE_BANNER,
    '<html lang="en">',
    "<head>",
    headMarkup,
    entry.output === "index.html"
      ? '<link rel="preload" as="image" href="/images/hero-archive-dish.webp" type="image/webp" fetchpriority="high" />'
      : "",
    renderStructuredData(structuredData),
    "</head>",
    `<body class="${entry.bodyClass}" data-site-url="${escapeAttribute(seoContext.siteUrl)}" data-home-card-hover-expand-enabled="${String(homeCardHoverExpandEnabled)}" data-shows-version="${versions.shows}" data-collections-version="${versions.collections}" data-search-index-version="${versions.searchIndex}">`,
    bodySections,
    "</body>",
    "</html>",
    "",
  ].join("\n");
}

function readJsonIfExists(filePath, fallbackValue) {
  try {
    return JSON.parse(readFile(filePath));
  } catch (_error) {
    return fallbackValue;
  }
}

function resolveCleanRouteAlias(entry) {
  if (!entry?.canonicalUrl) {
    return null;
  }

  let pathname = "";
  try {
    pathname = new URL(entry.canonicalUrl).pathname || "";
  } catch (_error) {
    return null;
  }

  if (!pathname || pathname === "/" || pathname.endsWith(".html")) {
    return null;
  }

  return pathname.replace(/^\/+/, "");
}

function shouldNoIndexAlias(cleanRouteAlias) {
  return NOINDEX_ALIAS_PATHS.has(cleanRouteAlias);
}

function resolveSiteUrl(manifest) {
  const configured = String(process.env.SITE_URL || "").trim();
  if (configured) {
    try {
      return new URL(configured).origin;
    } catch (_error) {
      throw new Error(`SITE_URL must be a valid absolute URL. Received: ${configured}`);
    }
  }

  const homeEntry = Array.isArray(manifest) ? manifest.find((entry) => entry.output === "index.html") : null;
  if (!homeEntry?.canonicalUrl) {
    return DEFAULT_SITE_URL;
  }

  try {
    return new URL(homeEntry.canonicalUrl).origin;
  } catch (_error) {
    return DEFAULT_SITE_URL;
  }
}

function resolveManifestCanonicalUrls(manifest, siteUrl) {
  return manifest.map((entry) => {
    let sourceUrl;
    try {
      sourceUrl = new URL(entry.canonicalUrl, `${siteUrl}/`);
    } catch (_error) {
      throw new Error(`Invalid canonical URL in page manifest for ${entry.output}: ${entry.canonicalUrl}`);
    }

    return {
      ...entry,
      canonicalUrl: new URL(`${sourceUrl.pathname}${sourceUrl.search}`, `${siteUrl}/`).toString(),
    };
  });
}

function createPrecacheUrlSet(manifest, versions) {
  const appModuleUrls = listFilesDeep(path.join(ROOT, "shared", "app"))
    .filter((filePath) => filePath.endsWith(".js") && path.basename(filePath) !== "app.js")
    .map((filePath) => `/${path.relative(ROOT, filePath).split(path.sep).join("/")}`);
  const precacheUrls = new Set([
    "/",
    "/offline.html",
    "/site.webmanifest",
    "/favicon.ico",
    "/apple-touch-icon.png",
    "/icon-192.png",
    "/icon-512.png",
    "/og-image.png",
    `/style.css?v=${versions.style}`,
    `/home.css?v=${versions.home}`,
    `/detail.css?v=${versions.extra.get("detail.css")}`,
    `/script.js?v=${versions.script}`,
    `/shared/app/app.js?v=${versions.app}`,
    `/shared/archive-record.js?v=${versions.archiveRecord}`,
    `/shared/archive-search.js?v=${versions.archiveSearch}`,
    getVersionedDataUrl("shows.json", versions.shows),
    getVersionedDataUrl("collections.json", versions.collections),
    getVersionedSearchIndexUrl(versions.searchIndex),
    ...appModuleUrls,
  ]);

  manifest.forEach((entry) => {
    if (entry.output.startsWith("maintainer/") || entry.noIndex) {
      return;
    }

    try {
      const canonicalPath = new URL(entry.canonicalUrl).pathname || "";
      if (canonicalPath && !["/collection", "/show"].includes(canonicalPath)) {
        precacheUrls.add(canonicalPath);
      }
    } catch (_error) {
      // Ignore malformed canonical URLs here; the page build still owns correctness.
    }
  });

  return [...precacheUrls].sort();
}

function renderServiceWorker({ versions, manifest }) {
  const precacheUrls = createPrecacheUrlSet(manifest, versions);
  const cacheVersion = hashBuffer(
    Buffer.from(
      JSON.stringify({
        script: versions.script,
        app: versions.app,
        style: versions.style,
        home: versions.home,
        detail: versions.extra.get("detail.css"),
        archiveRecord: versions.archiveRecord,
        archiveSearch: versions.archiveSearch,
        shows: versions.shows,
        collections: versions.collections,
        searchIndex: versions.searchIndex,
        precacheUrls,
      }),
    ),
  );

  return [
    GENERATED_JS_BANNER,
    `const CACHE_VERSION = "${cacheVersion}";`,
    'const HTML_CACHE = `echo-archives-html-${CACHE_VERSION}`;',
    'const ASSET_CACHE = `echo-archives-assets-${CACHE_VERSION}`;',
    `const PRECACHE_URLS = ${JSON.stringify(precacheUrls, null, 2)};`,
    'const OFFLINE_FALLBACK_URL = "/offline.html";',
    "",
    "self.addEventListener(\"install\", (event) => {",
    "  event.waitUntil(",
    "    caches.open(ASSET_CACHE).then((cache) => cache.addAll(PRECACHE_URLS)).then(() => self.skipWaiting()),",
    "  );",
    "});",
    "",
    "self.addEventListener(\"activate\", (event) => {",
    "  event.waitUntil(",
    "    caches",
    "      .keys()",
    "      .then((keys) => Promise.all(keys.filter((key) => key.startsWith(\"echo-archives-\") && key !== HTML_CACHE && key !== ASSET_CACHE).map((key) => caches.delete(key))))",
    "      .then(() => self.clients.claim()),",
    "  );",
    "});",
    "",
    "self.addEventListener(\"fetch\", (event) => {",
    "  const { request } = event;",
    "  if (request.method !== \"GET\") {",
    "    return;",
    "  }",
    "",
    "  const url = new URL(request.url);",
    "  if (url.origin !== self.location.origin || url.pathname.startsWith(\"/api/\")) {",
    "    return;",
    "  }",
    "",
    "  if (request.mode === \"navigate\") {",
    "    event.respondWith(handleNavigationRequest(request));",
    "    return;",
    "  }",
    "",
    "  event.respondWith(handleAssetRequest(request));",
    "});",
    "",
    "async function handleNavigationRequest(request) {",
    "  const cache = await caches.open(HTML_CACHE);",
    "",
    "  try {",
    "    const response = await fetch(request);",
    "    if (response && response.ok) {",
    "      void cache.put(request, response.clone());",
    "    }",
    "    return response;",
    "  } catch (_error) {",
    "    const cachedResponse = await cache.match(request);",
    "    if (cachedResponse) {",
    "      return cachedResponse;",
    "    }",
    "",
    "    const precachedFallback = await caches.match(request.url);",
    "    if (precachedFallback) {",
    "      return precachedFallback;",
    "    }",
    "",
    "    return caches.match(OFFLINE_FALLBACK_URL);",
    "  }",
    "}",
    "",
    "async function handleAssetRequest(request) {",
    "  const url = new URL(request.url);",
    "  if (shouldUseNetworkFirstAssetStrategy(request, url)) {",
    "    return handleNetworkFirstAssetRequest(request);",
    "  }",
    "",
    "  const cachedResponse = await caches.match(request);",
    "  if (cachedResponse) {",
    "    void refreshAssetCache(request);",
    "    return cachedResponse;",
    "  }",
    "",
    "  const response = await fetch(request);",
    "  if (response && response.ok) {",
    "    const cache = await caches.open(ASSET_CACHE);",
    "    void cache.put(request, response.clone());",
    "  }",
    "",
    "  return response;",
    "}",
    "",
    "function shouldUseNetworkFirstAssetStrategy(request, url) {",
    "  return request.destination === \"script\" || request.destination === \"style\" || /\\.(?:js|css)$/i.test(url.pathname);",
    "}",
    "",
    "async function handleNetworkFirstAssetRequest(request) {",
    "  try {",
    "    const response = await fetch(request);",
    "    if (response && response.ok) {",
    "      const cache = await caches.open(ASSET_CACHE);",
    "      void cache.put(request, response.clone());",
    "    }",
    "",
    "    return response;",
    "  } catch (_error) {",
    "    const cachedResponse = await caches.match(request);",
    "    if (cachedResponse) {",
    "      return cachedResponse;",
    "    }",
    "",
    "    throw _error;",
    "  }",
    "}",
    "",
    "async function refreshAssetCache(request) {",
    "  const cachedResponse = await caches.match(request);",
    "  try {",
    "    const response = await fetch(request);",
    "    if (!response || !response.ok) {",
    "      return;",
    "    }",
    "",
    "    const cache = await caches.open(ASSET_CACHE);",
    "    await cache.put(request, response.clone());",
    "  } catch (_error) {",
    "    // Keep the cached asset when refresh fails.",
    "  }",
    "}",
    "",
  ].join("\n");
}

function writeStaticSitemap({ siteUrl, catalog, collections }) {
  const sitemapXml = buildSitemapXml({ siteUrl, catalog, collections });
  writeFile(path.join(ROOT, "sitemap.xml"), `${sitemapXml}\n`);
}

function writeRobots({ siteUrl }) {
  const contents = [
    "User-agent: *",
    "Allow: /",
    "Disallow: /maintainer/",
    "",
    `Sitemap: ${new URL("/sitemap.xml", `${siteUrl}/`).toString()}`,
    "",
  ].join("\n");
  writeFile(path.join(ROOT, "robots.txt"), contents);
}

async function loadHomeConfig() {
  const homeConfigModuleUrl = pathToFileURL(path.join(ROOT, "shared", "app", "home-config.js")).href;
  const homeConfigModule = await import(homeConfigModuleUrl);
  return {
    homeMostPopularIds: Array.isArray(homeConfigModule.HOME_MOST_POPULAR_IDS) ? homeConfigModule.HOME_MOST_POPULAR_IDS : [],
    homeFavoriteRouteIds: Array.isArray(homeConfigModule.HOME_FAVORITE_ROUTE_IDS) ? homeConfigModule.HOME_FAVORITE_ROUTE_IDS : [],
  };
}

async function main() {
  buildEntryAssets();

  const versions = {
    app: hashTree("shared/app"),
    archiveRecord: hashFile("shared/archive-record.js"),
    archiveSearch: hashFile("shared/archive-search.js"),
    shows: hashFile("data/shows.json"),
    collections: hashFile("data/collections.json"),
    searchIndex: hashFile("data/search-index.json"),
    script: hashFile("script.js"),
    style: hashFile("style.css"),
    home: hashFile("home.css"),
    extra: new Map([
      ["detail.css", hashFile("detail.css")],
    ]),
  };
  const sourceManifest = JSON.parse(readFile(MANIFEST_PATH));
  const siteUrl = resolveSiteUrl(sourceManifest);
  const manifest = resolveManifestCanonicalUrls(sourceManifest, siteUrl);
  const catalog = readJsonIfExists(path.join(ROOT, "data", "shows.json"), []);
  const collections = readJsonIfExists(path.join(ROOT, "data", "collections.json"), []);
  const archiveStats = readJsonIfExists(path.join(ROOT, "data", "archive-stats.json"), {});
  const seoContext = { siteUrl, catalog, collections, archiveStats };
  const homeConfig = await loadHomeConfig();
  const partials = {
    head: readFile(path.join(PARTIALS_DIR, "head.html")).trim(),
    header: readFile(path.join(PARTIALS_DIR, "header.html")).trim(),
    floatingControls: readFile(path.join(PARTIALS_DIR, "floating-controls.html")).trim(),
    footer: readFile(path.join(PARTIALS_DIR, "footer.html")).trim(),
  };

  writeFile(path.join(ROOT, "sw.js"), renderServiceWorker({ versions, manifest }));
  writeStaticSitemap({ siteUrl, catalog, collections });
  writeRobots({ siteUrl });

  manifest.forEach((entry) => {
    const outputPath = path.join(ROOT, entry.output);
    const pageMarkup = renderPage(entry, partials, versions, homeConfig, seoContext);
    writeFile(outputPath, pageMarkup);

    const cleanRouteAlias = resolveCleanRouteAlias(entry);
    if (cleanRouteAlias) {
      const aliasMarkup = shouldNoIndexAlias(cleanRouteAlias)
        ? renderPage({ ...entry, noIndex: true }, partials, versions, homeConfig, seoContext)
        : pageMarkup;
      writeFile(path.join(ROOT, cleanRouteAlias, "index.html"), aliasMarkup);
    }
  });
}

if (require.main === module) {
  main().catch((error) => {
    console.error(error);
    process.exitCode = 1;
  });
}

module.exports = {
  resolveManifestCanonicalUrls,
  resolveSiteUrl,
  serializeStructuredData,
};
