const crypto = require("node:crypto");
const fs = require("node:fs");
const path = require("node:path");
const { pathToFileURL } = require("node:url");

const { buildSitemapXml } = require("../backend/lib/sitemap");
const { BRAND_DESCRIPTOR, DEFAULT_DESCRIPTION } = require("../backend/lib/seo");
const { generateStaticImageVariants } = require("../backend/lib/responsive-images");
const { renderCollectionsPagePrerender, renderHomePagePrerender } = require("./lib/home-page-prerender");

const ROOT = path.resolve(__dirname, "..");
const BUILD_ENV_PATH = path.join(ROOT, "backend", ".env");
const SITE_SRC = path.join(ROOT, "site-src");
const PARTIALS_DIR = path.join(SITE_SRC, "partials");
const PAGES_DIR = path.join(SITE_SRC, "pages");
const MANIFEST_PATH = path.join(SITE_SRC, "page-manifest.json");
const SOCIAL_LINKS_PATH = path.join(SITE_SRC, "data", "social-links.json");
const GENERATED_PAGE_BANNER = "<!-- Generated from site-src by tools/build-pages.js. Do not edit this file directly. -->";
const GENERATED_JS_BANNER = "// Generated from tools/build-pages.js. Do not edit this file directly.";
const GENERATED_CSS_BANNER = "/* Generated from tools/build-pages.js. Do not edit this file directly. */";
const DEFAULT_PLAUSIBLE_SCRIPT_SRC = "https://plausible.io/js/script.js";
const DEFAULT_SITE_URL = "https://echoarchives.net";
const DEFAULT_SOCIAL_IMAGE_ALT = "The Echo Archives social preview";
const NOINDEX_ALIAS_PATHS = new Set(["show", "collection"]);

function loadBuildEnvironment() {
  if (!fs.existsSync(BUILD_ENV_PATH)) {
    return;
  }

  if (typeof process.loadEnvFile !== "function") {
    throw new Error("Loading backend/.env requires Node 22.12 or newer.");
  }

  process.loadEnvFile(BUILD_ENV_PATH);
}

loadBuildEnvironment();

const ENTRY_ASSETS = {
  "script.js": ({ appVersion }) => [
    GENERATED_JS_BANNER,
    `import { initializeApp } from "./shared/app/app.js?v=${appVersion}";`,
    "",
    "initializeApp().catch((error) => {",
    '  const mismatchMessage = String(error?.message || "");',
    `  const recoveryKey = "echo-archives-module-recovery-${appVersion}-" + encodeURIComponent(mismatchMessage.slice(0, 180));`,
    '  const isModuleVersionMismatch = /does not provide an export named/.test(mismatchMessage);',
    "  if (isModuleVersionMismatch && !sessionStorage.getItem(recoveryKey)) {",
    "    sessionStorage.setItem(recoveryKey, \"1\");",
    "    void caches.keys()",
    '      .then((keys) => Promise.all(keys.filter((key) => key.startsWith("echo-archives-")).map((key) => caches.delete(key))))',
    "      .finally(() => window.location.reload());",
    "    return;",
    "  }",
    '  console.error("Failed to initialize the Echo Archives app.", error);',
    "});",
    "",
  ].join("\n"),
  "style.css": () => renderCssBundle([
    "shared/styles/base/variables.css",
    "shared/styles/base/global.css",
    "shared/styles/base/header-footer.css",
    "shared/styles/home/cards/01-surface.css",
    "shared/styles/home/cards/02-hero-search.css",
    "shared/styles/home/cards/07-archive-cards.css",
    "shared/styles/home/cards/08-footer.css",
    "shared/styles/home/cards/11-community-rating.css",
    "shared/styles/home/cards/13-chat-about-base.css",
    "shared/styles/home/cards/16-empty-tablet.css",
    "shared/styles/home/cards/17-responsive-780-a.css",
    "shared/styles/home/cards/18-responsive-780-b.css",
    "shared/styles/home/cards/19-responsive-560.css",
    "shared/styles/home/cards/20-motion.css",
    "shared/styles/base/responsive-robustness.css",
  ]),
  "public-heroes.css": () => renderCssBundle([
    "shared/styles/home/public-heroes.css",
  ]),
  "home.css": () => renderCssBundle([
    "shared/styles/home/cards/02a-sticky-browse.css",
    "shared/styles/home/cards/03-filter-controls.css",
    "shared/styles/home/cards/03a-filter-detail-controls.css",
    "shared/styles/home/cards/03b-filter-actions.css",
    "shared/styles/home/cards/04-browse-bands.css",
    "shared/styles/home/cards/06-featured-cards.css",
    "shared/styles/home/cards/09-preview-shell.css",
    "shared/styles/home/cards/10-preview-content.css",
    "shared/styles/home/cards/16-empty-tablet.css",
    "shared/styles/home/cards/17-responsive-780-a.css",
    "shared/styles/home/cards/18-responsive-780-b.css",
    "shared/styles/home/cards/19-responsive-560.css",
    "shared/styles/base/responsive-robustness.css",
  ]),
  "info.css": () => renderCssBundle([
    "shared/styles/home/cards/14-about-features.css",
    "shared/styles/home/cards/14b-about-page-polish.css",
    "shared/styles/home/cards/15-about-supporters.css",
    "shared/styles/home/cards/15b-info-pages.css",
    "shared/styles/home/cards/15c-info-pages-responsive.css",
    "shared/styles/home/cards/15d-help-center.css",
    "shared/styles/home/cards/15e-help-center-motion.css",
    "shared/styles/base/responsive-robustness.css",
  ]),
  "submit.css": () => renderCssBundle([
    "shared/styles/home/submit.css",
    "shared/styles/base/responsive-robustness.css",
  ]),
  "maintainer.css": () => renderCssBundle([
    "shared/styles/home/maintainer.css",
    "shared/styles/base/responsive-robustness.css",
  ]),
  "collections.css": () => renderCssBundle([
    "shared/styles/home/cards/05-collection-cards.css",
    "shared/styles/home/collections.css",
    "shared/styles/base/responsive-robustness.css",
  ]),
  "creators.css": () => renderCssBundle([
    "shared/styles/home/creators.css",
    "shared/styles/base/responsive-robustness.css",
  ]),
  "chat.css": () => renderCssBundle([
    "shared/styles/base/global/03-responsive.css",
    "shared/styles/home/cards/11-community-rating.css",
    "shared/styles/home/cards/12-chat-panel.css",
    "shared/styles/home/cards/13-chat-about-base.css",
    "shared/styles/home/chat-responsive.css",
    "shared/styles/base/responsive-robustness.css",
  ]),
  "detail.css": () => renderCssBundle([
    "shared/styles/show/hero.css",
    "shared/styles/show/sections.css",
    "shared/styles/show/facts-rail.css",
    "shared/styles/show/community.css",
    "shared/styles/show/responsive.css",
    "shared/styles/base/responsive-robustness.css",
  ]),
};

function readFile(filePath) {
  return fs.readFileSync(filePath, "utf8");
}

function writeFile(filePath, contents) {
  fs.mkdirSync(path.dirname(filePath), { recursive: true });
  fs.writeFileSync(filePath, String(contents).replace(/[ \t]+$/gm, ""));
}

function rewriteCssAssetUrls(contents, sourcePath) {
  return contents.replace(/url\(\s*(["']?)([^"')]+)\1\s*\)/gi, (match, quote, rawValue) => {
    const value = String(rawValue || "").trim();
    if (!value || /^(?:[a-z]+:|\/\/|\/|#)/i.test(value)) {
      return match;
    }

    const suffixIndex = value.search(/[?#]/);
    const pathname = suffixIndex >= 0 ? value.slice(0, suffixIndex) : value;
    const suffix = suffixIndex >= 0 ? value.slice(suffixIndex) : "";
    const resolvedPath = path.resolve(path.dirname(sourcePath), pathname);
    const relativePath = path.relative(ROOT, resolvedPath);
    if (relativePath.startsWith("..") || path.isAbsolute(relativePath)) {
      throw new Error(`CSS asset escapes the public root: ${value} in ${path.relative(ROOT, sourcePath)}`);
    }

    const publicUrl = `/${relativePath.split(path.sep).join("/")}${suffix}`;
    const renderedQuote = quote || '"';
    return `url(${renderedQuote}${publicUrl}${renderedQuote})`;
  });
}

function flattenCssFile(filePath, ancestry = []) {
  const normalizedPath = path.resolve(filePath);
  if (ancestry.includes(normalizedPath)) {
    const cycle = [...ancestry, normalizedPath].map((entry) => path.relative(ROOT, entry)).join(" -> ");
    throw new Error(`Circular CSS import detected: ${cycle}`);
  }

  const nextAncestry = [...ancestry, normalizedPath];
  const contents = readFile(normalizedPath);
  const flattened = contents.replace(
    /@import\s+(?:url\(\s*)?["']([^"']+)["']\s*\)?\s*;/gi,
    (_match, importValue) => {
      const relativeImport = stripQuery(importValue);
      if (/^(?:[a-z]+:|\/\/|\/)/i.test(relativeImport)) {
        throw new Error(`External or root CSS import cannot be flattened: ${importValue}`);
      }

      const importedPath = path.resolve(path.dirname(normalizedPath), relativeImport);
      return flattenCssFile(importedPath, nextAncestry);
    },
  );

  return [
    `/* Source: ${path.relative(ROOT, normalizedPath).split(path.sep).join("/")} */`,
    rewriteCssAssetUrls(flattened, normalizedPath).trim(),
  ].join("\n");
}

function renderCssBundle(relativePaths) {
  const contents = `${[
    GENERATED_CSS_BANNER,
    ...relativePaths.map((relativePath) => flattenCssFile(path.join(ROOT, relativePath))),
  ]
    .join("\n\n")
    .replace(/[ \t]+$/gm, "")
    .trimEnd()}\n`;

  if (/@import\b/i.test(contents)) {
    throw new Error("Generated CSS bundle still contains an @import rule.");
  }

  return contents;
}

function hashBuffer(buffer) {
  return crypto.createHash("sha1").update(buffer).digest("hex").slice(0, 10);
}

function listFilesDeep(startPath) {
  const results = [];

  if (!fs.existsSync(startPath)) {
    return results;
  }

  function walk(currentPath) {
    fs.readdirSync(currentPath, { withFileTypes: true }).forEach((entry) => {
      const absolutePath = path.join(currentPath, entry.name);
      if (entry.isDirectory()) {
        walk(absolutePath);
        return;
      }

      results.push(absolutePath);
    });
  }

  walk(startPath);
  return results.sort((left, right) => left.localeCompare(right));
}

function hashFile(relativePath) {
  return hashBuffer(fs.readFileSync(path.join(ROOT, relativePath)));
}

function hashTree(relativePath) {
  const files = listFilesDeep(path.join(ROOT, relativePath));
  const hash = crypto.createHash("sha1");

  files.forEach((filePath) => {
    hash.update(path.relative(ROOT, filePath));
    hash.update(fs.readFileSync(filePath));
  });

  return hash.digest("hex").slice(0, 10);
}

function stripQuery(value = "") {
  return String(value || "").split("?", 1)[0];
}

function withVersion(relativePath, version) {
  return `${relativePath}?v=${version}`;
}

function getVersionedSearchIndexUrl(version) {
  return `/${withVersion("data/search-index.json", version)}`;
}

function getVersionedDataUrl(fileName, version) {
  return `/${withVersion(`data/${fileName}`, version)}`;
}

function renderTemplate(template, replacements) {
  return renderConditionals(template, replacements).replace(/\{\{([a-zA-Z0-9]+)\}\}/g, (_match, key) => replacements[key] ?? "");
}

function renderConditionals(template, replacements) {
  return template.replace(
    /\{\{#([a-zA-Z0-9]+)\}\}([\s\S]*?)\{\{\/\1\}\}/g,
    (_match, key, contents) => (replacements[key] ? contents : ""),
  );
}

function escapeAttribute(value = "") {
  return String(value)
    .replace(/&/g, "&amp;")
    .replace(/"/g, "&quot;");
}

function escapeHtml(value = "") {
  return String(value)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;");
}

function escapeRegExp(value = "") {
  return String(value).replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

function parseBoolean(value, fallback = false) {
  if (value === undefined) {
    return fallback;
  }

  return /^(1|true|yes|on)$/i.test(String(value).trim());
}

function renderStylesheets(extraStylesheets = [], versions = {}) {
  const publicHeroStylesheet = "public-heroes.css";
  return [
    `<link rel="stylesheet" href="/style.css?v=${versions.style}" />`,
    ...extraStylesheets.map((href) => {
      const basePath = stripQuery(href);
      const version = versions.extra.get(basePath) || hashFile(basePath);
      return `<link rel="stylesheet" href="/${withVersion(basePath, version)}" />`;
    }),
    `<link rel="stylesheet" href="/${withVersion(publicHeroStylesheet, versions.extra.get(publicHeroStylesheet))}" />`,
  ].join("\n");
}

function renderRobotsMeta(entry) {
  return entry.noIndex
    ? '<meta name="robots" content="noindex, nofollow, noarchive" />'
    : '<meta name="robots" content="index, follow, max-image-preview:large" />';
}

function renderAnalyticsScript(entry) {
  const plausibleDomain = String(process.env.PLAUSIBLE_DOMAIN || "").trim();
  if (!plausibleDomain || entry.includeAnalytics === false) {
    return "";
  }

  const plausibleScriptSrc = String(process.env.PLAUSIBLE_SCRIPT_SRC || DEFAULT_PLAUSIBLE_SCRIPT_SRC).trim();
  if (!plausibleScriptSrc) {
    return "";
  }

  return `<script defer data-domain="${escapeAttribute(plausibleDomain)}" src="${escapeAttribute(plausibleScriptSrc)}"></script>`;
}

const PRIMARY_NAV_ITEMS = [
    { id: "browse", label: "Browse", detail: "All shows and archive filters", href: "/" },
    { id: "collections", label: "Collections", detail: "Shows grouped by mood and theme", href: "/collections" },
    { id: "about", label: "About", detail: "What the archive is building", href: "/about" },
    { id: "submit", label: "Submit", detail: "Add shows or send corrections", href: "/submit" },
    { id: "for-creators", label: "For creators", detail: "Verification and standards", href: "/for-creators" },
];

const MOBILE_DRAWER_SECTIONS = [
  {
    label: "Explore",
    items: [
      { id: "browse", label: "Browse", href: "/", icon: "search" },
      { id: "collections", label: "Collections", href: "/collections", icon: "folder" },
      { id: "about", label: "About", href: "/about", icon: "info" },
    ],
  },
  {
    label: "Contribute",
    items: [
      { id: "submit", label: "Submit a show", href: "/submit", icon: "plus" },
      { id: "for-creators", label: "For creators", href: "/for-creators", icon: "person" },
      { id: "creator-standards", label: "Creator standards", href: "/creator-standards", icon: "shield" },
    ],
  },
  {
    label: "Archive support",
    items: [
      { id: "supporters", label: "Support the archive", href: "/supporters", icon: "heart" },
      { id: "help-center", label: "Help Center", href: "/help-center", icon: "help" },
      { id: "contact", label: "Contact", href: "https://contact.continental-hub.com/", icon: "mail" },
    ],
  },
  {
    label: "Policies",
    items: [
      { id: "privacy", label: "Privacy", href: "/privacy", icon: "document" },
      { id: "terms", label: "Terms", href: "/terms", icon: "document" },
      { id: "cookies", label: "Cookies", href: "/cookies", icon: "document" },
      { id: "copyright", label: "Copyright & takedown", href: "/copyright", icon: "document" },
    ],
  },
];

const MOBILE_NAV_ICONS = {
  search: '<path d="m20 20-4.35-4.35M10.75 18a7.25 7.25 0 1 1 0-14.5 7.25 7.25 0 0 1 0 14.5Z" />',
  folder: '<path d="M3 7.75A2.75 2.75 0 0 1 5.75 5h4.12l1.8 2.1H18.25A2.75 2.75 0 0 1 21 9.85v7.4A2.75 2.75 0 0 1 18.25 20H5.75A2.75 2.75 0 0 1 3 17.25v-9.5Z" />',
  info: '<circle cx="12" cy="12" r="8.5" /><path d="M12 10.8v5M12 7.8h.01" />',
  plus: '<circle cx="12" cy="12" r="8.5" /><path d="M12 8v8M8 12h8" />',
  person: '<circle cx="12" cy="8.1" r="3" /><path d="M5.4 20c.65-3.45 2.82-5.2 6.6-5.2s5.95 1.75 6.6 5.2" />',
  shield: '<path d="M12 3.3 19 6v5.28c0 4.18-2.48 7.42-7 9.42-4.52-2-7-5.24-7-9.42V6l7-2.7Z" /><path d="m8.8 12 2.08 2.08L15.5 9.5" />',
  heart: '<path d="M20.45 8.48c0 5.1-8.45 10.22-8.45 10.22S3.55 13.58 3.55 8.48c0-2.52 1.76-4.28 4.12-4.28 1.65 0 3.2.9 4.33 2.4 1.13-1.5 2.68-2.4 4.33-2.4 2.36 0 4.12 1.76 4.12 4.28Z" />',
  help: '<circle cx="12" cy="12" r="8.5" /><path d="M9.55 9.45a2.62 2.62 0 1 1 4.72 1.6c-.98 1.25-2.27 1.5-2.27 3.2M12 16.9h.01" />',
  mail: '<rect x="3.5" y="5.5" width="17" height="13" rx="2" /><path d="m4.5 7 7.5 5.75L19.5 7" />',
  document: '<path d="M7 3.5h6.2l3.8 3.8v12.2a1.5 1.5 0 0 1-1.5 1.5h-8A1.5 1.5 0 0 1 6 19.5v-14A2 2 0 0 1 7 3.5Z" /><path d="M13 3.8v3.8h3.8M9 13h6M9 16h4.5" />',
};

function renderNavLinks(activeNav) {
  return PRIMARY_NAV_ITEMS
    .map((item) => renderDesktopNavLink(item, item.id === activeNav))
    .join("\n    ");
}

function renderDesktopNavLink(item, isActive) {
  const activeClass = isActive ? ' class="is-active"' : "";
  const currentPage = isActive ? ' aria-current="page"' : "";
  return `<a${activeClass}${currentPage} href="${item.href}"><span class="site-nav-link-body"><span class="site-nav-link-label">${item.label}</span><span class="site-nav-link-detail">${item.detail}</span></span><span class="site-nav-link-arrow" aria-hidden="true"></span></a>`;
}

function getCanonicalPath(entry) {
  try {
    return new URL(entry.canonicalUrl, "https://echoarchives.net").pathname;
  } catch (_error) {
    return "";
  }
}

function isMobileNavItemActive(item, entry, directPaths) {
  const canonicalPath = getCanonicalPath(entry);
  if (directPaths.has(canonicalPath)) {
    return item.href === canonicalPath;
  }
  return item.id === entry.activeNav;
}

function renderMobilePrimaryNav(entry) {
  const mobileItems = ["browse", "collections", "submit", "about"]
    .map((id) => PRIMARY_NAV_ITEMS.find((item) => item.id === id))
    .filter(Boolean);
  const directPaths = new Set(mobileItems.map((item) => item.href));
  return mobileItems
    .map((item) => {
      const isActive = isMobileNavItemActive(item, entry, directPaths);
      return `<a${isActive ? ' class="is-active" aria-current="page"' : ""} href="${item.href}">${item.label}</a>`;
    })
    .join("\n    ");
}

function renderMobileDrawerNav(entry) {
  const allItems = MOBILE_DRAWER_SECTIONS.flatMap((section) => section.items);
  const directPaths = new Set(allItems.map((item) => item.href).filter((href) => href.startsWith("/")));

  return `<nav class="site-mobile-drawer-nav" aria-label="Full site navigation">${MOBILE_DRAWER_SECTIONS.map((section) => `
        <section class="site-mobile-nav-section" aria-labelledby="site-mobile-nav-${section.label.toLowerCase().replace(/[^a-z]+/g, "-")}">
          <h2 id="site-mobile-nav-${section.label.toLowerCase().replace(/[^a-z]+/g, "-")}" class="site-mobile-nav-section-title">${section.label}</h2>
          <div class="site-mobile-nav-links">
            ${section.items.map((item) => renderMobileDrawerLink(item, isMobileNavItemActive(item, entry, directPaths))).join("\n            ")}
          </div>
        </section>`).join("\n")}
      </nav>`;
}

function renderMobileDrawerLink(item, isActive) {
  const activeClass = isActive ? " is-active" : "";
  const currentPage = isActive ? ' aria-current="page"' : "";
  const icon = MOBILE_NAV_ICONS[item.icon] || MOBILE_NAV_ICONS.document;
  return `<a class="site-mobile-nav-link${activeClass}"${currentPage} href="${item.href}"><svg class="site-mobile-nav-icon" viewBox="0 0 24 24" aria-hidden="true">${icon}</svg><span>${item.label}</span></a>`;
}

function renderSocialLinks(socialLinks = []) {
  return socialLinks.map(({ name, url, icon }) => {
    const label = String(name || "").trim();
    const href = String(url || "").trim();
    const iconFile = String(icon || "").trim();

    if (!label || !/^https:\/\//i.test(href) || !/^[a-z0-9-]+\.svg$/i.test(iconFile)) {
      throw new Error("Each social link requires a name, an HTTPS URL, and an SVG icon filename.");
    }

    return `          <li><a class="footer-social-link" href="${escapeAttribute(href)}" target="_blank" rel="noreferrer" aria-label="Follow The Echo Archives on ${escapeAttribute(label)}"><img src="/images/social/${escapeAttribute(iconFile)}" alt="" width="25" height="25" /></a></li>`;
  }).join("\n");
}

function resolveMainContentTarget(entry) {
  return entry.source === "show.html" ? "showRoot" : "main-content";
}

function renderSkipLink(targetId) {
  return `<a class="skip-link" href="#${escapeAttribute(targetId)}">Skip to main content</a>`;
}

function ensureMainContentTarget(pageBody, targetId) {
  if (!targetId) {
    return pageBody;
  }

  const existingTargetPattern = new RegExp(`<main\\b([^>]*\\bid="${escapeRegExp(targetId)}"[^>]*)>`, "i");
  if (existingTargetPattern.test(pageBody)) {
    return pageBody.replace(existingTargetPattern, (match, attributes) => {
      if (/\btabindex=/.test(attributes)) {
        return match;
      }

      return `<main${attributes} tabindex="-1">`;
    });
  }

  return pageBody.replace(/<main\b(?![^>]*\bid=)/i, `<main id="${escapeAttribute(targetId)}" tabindex="-1"`);
}

function replaceElementTextById(html, id, value) {
  const pattern = new RegExp(`(<([a-z][a-z0-9-]*)\\b[^>]*\\bid="${escapeRegExp(id)}"[^>]*>)[\\s\\S]*?(<\\/\\2>)`, "i");
  return html.replace(pattern, `$1${escapeHtml(value)}$3`);
}

function replaceElementMarkupById(html, id, value) {
  const pattern = new RegExp(`(<([a-z][a-z0-9-]*)\\b[^>]*\\bid="${escapeRegExp(id)}"[^>]*>)[\\s\\S]*?(<\\/\\2>)`, "i");
  return html.replace(pattern, `$1${value}$3`);
}

function formatLongDate(value) {
  const match = /^(\d{4})-(\d{2})-(\d{2})$/.exec(String(value || "").trim());
  if (!match) {
    return value ? "Date needs review" : "Unknown";
  }

  const [, year, month, day] = match;
  const date = new Date(Number(year), Number(month) - 1, Number(day));
  if (
    date.getFullYear() !== Number(year) ||
    date.getMonth() !== Number(month) - 1 ||
    date.getDate() !== Number(day)
  ) {
    return "Date needs review";
  }

  return new Intl.DateTimeFormat("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  }).format(date);
}

function prerenderArchiveStats(pageBody, entry, archiveStats) {
  const stats = archiveStats && typeof archiveStats === "object" ? archiveStats : {};
  if (!Number.isFinite(Number(stats.showCount))) {
    return pageBody;
  }
  const valuesByOutput = {
    "about.html": {
      aboutShowCount: Number(stats.showCount) || 0,
      aboutReviewCount: Number(stats.fullReviewCount) || 0,
      aboutCollectionCount: Number(stats.collectionCount) || 0,
      aboutLastUpdated: formatLongDate(stats.latestUpdatedAt),
    },
    "for-creators.html": {
      creatorsCreatorCount: Number(stats.creatorCount) || 0,
      creatorsShowCount: Number(stats.showCount) || 0,
      creatorsMetadataCount: Number(stats.metadataCheckedCount) || 0,
      creatorsReviewCount: Number(stats.fullReviewCount) || 0,
      creatorsLastUpdated: formatLongDate(stats.latestUpdatedAt),
    },
  };
  const values = valuesByOutput[entry.output];
  if (!values) {
    return pageBody;
  }

  return Object.entries(values).reduce(
    (rendered, [id, value]) => replaceElementTextById(rendered, id, value),
    pageBody,
  );
}

function renderPageBody(entry, homeConfig, archiveStats, submitPrerender, archivistEnabled) {
  let pageBody = renderConditionals(
    ensureMainContentTarget(readFile(path.join(PAGES_DIR, entry.source)).trim(), resolveMainContentTarget(entry)),
    { archivist: archivistEnabled },
  );

  if (entry.output === "index.html") {
    pageBody = renderHomePagePrerender(pageBody, {
      rootDir: ROOT,
      homeMostPopularIds: homeConfig.homeMostPopularIds,
      homeFavoriteRouteIds: homeConfig.homeFavoriteRouteIds,
    });
  }

  if (entry.output === "collections.html") {
    pageBody = renderCollectionsPagePrerender(pageBody, { rootDir: ROOT });
  }

  if (entry.output === "submit.html" && submitPrerender) {
    Object.entries(submitPrerender).forEach(([id, markup]) => {
      pageBody = replaceElementMarkupById(pageBody, id, markup);
    });
  }

  return prerenderArchiveStats(pageBody, entry, archiveStats);
}

function buildEntryAssets() {
  const nestedVersions = {
    appVersion: hashTree("shared/app"),
    baseVersion: hashTree("shared/styles/base"),
    homeVersion: hashTree("shared/styles/home"),
    submitVersion: hashTree("shared/styles/home/submit"),
    collectionsVersion: hashTree("shared/styles/home/collections"),
    creatorsVersion: hashTree("shared/styles/home/creators"),
    showVersion: hashTree("shared/styles/show"),
  };

  Object.entries(ENTRY_ASSETS).forEach(([fileName, render]) => {
    writeFile(path.join(ROOT, fileName), render(nestedVersions));
  });
}

function serializeStructuredData(value) {
  return JSON.stringify(value)
    .replace(/</g, "\\u003c")
    .replace(/\u2028/g, "\\u2028")
    .replace(/\u2029/g, "\\u2029");
}

function renderStructuredData(value) {
  if (!value) {
    return "";
  }
  return `<script id="pageStructuredData" type="application/ld+json">${serializeStructuredData(value)}</script>`;
}

function buildCollectionsStructuredData({ siteUrl, entry, collections }) {
  const homeUrl = new URL("/", `${siteUrl}/`).toString();
  const pageUrl = entry.canonicalUrl;
  return {
    "@context": "https://schema.org",
    "@graph": [
      {
        "@type": "CollectionPage",
        "@id": `${pageUrl}#webpage`,
        name: entry.title,
        description: entry.description,
        url: pageUrl,
        isPartOf: { "@id": `${homeUrl}#website` },
        breadcrumb: { "@id": `${pageUrl}#breadcrumb` },
        mainEntity: { "@id": `${pageUrl}#itemlist` },
      },
      {
        "@type": "ItemList",
        "@id": `${pageUrl}#itemlist`,
        numberOfItems: collections.length,
        itemListElement: collections.map((collection, index) => ({
          "@type": "ListItem",
          position: index + 1,
          name: collection.title,
          url: new URL(`/collections/${encodeURIComponent(collection.id)}`, `${siteUrl}/`).toString(),
        })),
      },
      {
        "@type": "BreadcrumbList",
        "@id": `${pageUrl}#breadcrumb`,
        itemListElement: [
          { "@type": "ListItem", position: 1, name: BRAND_DESCRIPTOR, item: homeUrl },
          { "@type": "ListItem", position: 2, name: "Curated audio drama collections", item: pageUrl },
        ],
      },
    ],
  };
}

function buildPageStructuredData({ siteUrl, entry, collections }) {
  if (entry.output === "index.html") {
    const homeUrl = new URL("/", `${siteUrl}/`).toString();
    return {
      "@context": "https://schema.org",
      "@graph": [
        {
          "@type": "WebSite",
          "@id": `${homeUrl}#website`,
          name: "The Echo Archives",
          alternateName: BRAND_DESCRIPTOR,
          url: homeUrl,
          description: entry.description,
          about: [
            { "@type": "Thing", name: "Audio drama discovery" },
            { "@type": "Thing", name: "Fiction podcast recommendations" },
            { "@type": "Thing", name: "Audio drama reviews" },
          ],
          potentialAction: {
            "@type": "SearchAction",
            target: {
              "@type": "EntryPoint",
              urlTemplate: `${homeUrl}?q={search_term_string}#archive`,
            },
            "query-input": "required name=search_term_string",
          },
        },
        {
          "@type": "WebPage",
          "@id": `${homeUrl}#webpage`,
          url: homeUrl,
          name: BRAND_DESCRIPTOR,
          description: entry.description || DEFAULT_DESCRIPTION,
          isPartOf: { "@id": `${homeUrl}#website` },
        },
      ],
    };
  }

  if (entry.output === "collections.html") {
    return buildCollectionsStructuredData({ siteUrl, entry, collections });
  }

  if (entry.noIndex) return null;
  const homeUrl = new URL("/", `${siteUrl}/`).toString();
  const pageUrl = entry.canonicalUrl;
  return {
    "@context": "https://schema.org",
    "@graph": [
      {
        "@type": "WebPage",
        "@id": `${pageUrl}#webpage`,
        url: pageUrl,
        name: entry.title,
        description: entry.description,
        isPartOf: { "@id": `${homeUrl}#website` },
        breadcrumb: { "@id": `${pageUrl}#breadcrumb` },
      },
      {
        "@type": "BreadcrumbList",
        "@id": `${pageUrl}#breadcrumb`,
        itemListElement: [
          { "@type": "ListItem", position: 1, name: BRAND_DESCRIPTOR, item: homeUrl },
          { "@type": "ListItem", position: 2, name: entry.title, item: pageUrl },
        ],
      },
    ],
  };
}

function renderPage(entry, partials, versions, homeConfig, seoContext, submitPrerender) {
  const homeCardHoverExpandEnabled = parseBoolean(process.env.HOME_CARD_HOVER_EXPAND_ENABLED, false);
  const archivistEnabled = parseBoolean(process.env.ARCHIVIST_ENABLED, false);
  const socialImageUrl = new URL("/echo-wordmark1.png", `${seoContext.siteUrl}/`).toString();
  const structuredData = buildPageStructuredData({
    siteUrl: seoContext.siteUrl,
    entry,
    collections: seoContext.collections,
  });
  const headMarkup = renderTemplate(partials.head, {
    title: entry.title,
    description: entry.description,
    canonicalUrl: entry.canonicalUrl,
    socialImageUrl,
    socialImageAlt: DEFAULT_SOCIAL_IMAGE_ALT,
    robotsMeta: renderRobotsMeta(entry),
    analyticsScript: renderAnalyticsScript(entry),
    scrollRestorationScript: ["index.html", "collections.html"].includes(entry.source)
      ? `<script src="/shared/app/scroll-restoration-boot.js?v=${versions.scrollRestorationBoot}"></script>`
      : "",
    stylesheets: renderStylesheets(entry.extraStylesheets, versions),
  });
  const headerMarkup = renderTemplate(partials.header, {
    navLinks: renderNavLinks(entry.activeNav),
    mobilePrimaryNav: renderMobilePrimaryNav(entry),
    mobileDrawerNav: renderMobileDrawerNav(entry),
  });
  const mainContentTarget = resolveMainContentTarget(entry);
  const pageBody = renderPageBody(entry, homeConfig, seoContext.archiveStats, submitPrerender, archivistEnabled);
  const bodySections = [
    renderSkipLink(mainContentTarget),
    headerMarkup,
    pageBody,
    entry.includeFloatingControls
      ? renderConditionals(partials.floatingControls, { archivist: archivistEnabled })
      : "",
    partials.footer,
    `  <script src="/shared/archive-record.js?v=${versions.archiveRecord}"></script>`,
    `  <script src="/shared/archive-search.js?v=${versions.archiveSearch}"></script>`,
    `  <script type="module" src="/script.js?v=${versions.script}"></script>`,
  ]
    .filter(Boolean)
    .join("\n\n");

  return [
    "<!DOCTYPE html>",
    GENERATED_PAGE_BANNER,
    '<html lang="en">',
    "<head>",
    headMarkup,
    entry.output === "index.html"
      ? '<link rel="preload" as="image" href="/images/hero-archive-dish.webp" type="image/webp" fetchpriority="high" />'
      : "",
    renderStructuredData(structuredData),
    "</head>",
    `<body class="${entry.bodyClass}" data-site-url="${escapeAttribute(seoContext.siteUrl)}" data-chat-stylesheet="/chat.css?v=${versions.extra.get("chat.css")}" data-archivist-enabled="${String(archivistEnabled)}" data-home-card-hover-expand-enabled="${String(homeCardHoverExpandEnabled)}" data-shows-version="${versions.shows}" data-collections-version="${versions.collections}" data-search-index-version="${versions.searchIndex}">`,
    bodySections,
    "</body>",
    "</html>",
    "",
  ].join("\n");
}

function readJsonIfExists(filePath, fallbackValue) {
  try {
    return JSON.parse(readFile(filePath));
  } catch (_error) {
    return fallbackValue;
  }
}

function resolveCleanRouteAlias(entry) {
  if (!entry?.canonicalUrl) {
    return null;
  }

  let pathname = "";
  try {
    pathname = new URL(entry.canonicalUrl, DEFAULT_SITE_URL).pathname || "";
  } catch (_error) {
    return null;
  }

  if (!pathname || pathname === "/" || pathname.endsWith(".html")) {
    return null;
  }

  return pathname.replace(/^\/+/, "");
}

function shouldNoIndexAlias(cleanRouteAlias) {
  return NOINDEX_ALIAS_PATHS.has(cleanRouteAlias);
}

function resolveSiteUrl(manifest) {
  const configured = String(process.env.SITE_URL || "").trim();
  if (configured) {
    try {
      return new URL(configured).origin;
    } catch (_error) {
      throw new Error(`SITE_URL must be a valid absolute URL. Received: ${configured}`);
    }
  }

  const homeEntry = Array.isArray(manifest) ? manifest.find((entry) => entry.output === "index.html") : null;
  if (!homeEntry?.canonicalUrl) {
    return DEFAULT_SITE_URL;
  }

  try {
    return new URL(homeEntry.canonicalUrl).origin;
  } catch (_error) {
    return DEFAULT_SITE_URL;
  }
}

function resolveManifestCanonicalUrls(manifest, siteUrl) {
  return manifest.map((entry) => {
    let sourceUrl;
    try {
      sourceUrl = new URL(entry.canonicalUrl, `${siteUrl}/`);
    } catch (_error) {
      throw new Error(`Invalid canonical URL in page manifest for ${entry.output}: ${entry.canonicalUrl}`);
    }

    return {
      ...entry,
      canonicalUrl: new URL(`${sourceUrl.pathname}${sourceUrl.search}`, `${siteUrl}/`).toString(),
    };
  });
}

function createPrecacheUrlSet(_manifest, versions) {
  const offlineAppModuleUrls = [
    "constants.js",
    "home-config.js",
    "images.js",
    "mobile-nav.js",
    "service-worker.js",
    "toast.js",
    "utils.js",
    "viewport-metrics.js",
  ].map((fileName) => `/shared/app/${fileName}`);
  const precacheUrls = new Set([
    "/offline.html",
    "/site.webmanifest",
    "/favicon.ico",
    "/apple-touch-icon.png",
    "/icon-192.png",
    "/icon-512.png",
    "/echo-wordmark1.png",
    "/echo-wordmark-nosub1.svg",
    "/echo-wordmark-sub1.svg",
    `/style.css?v=${versions.style}`,
    `/public-heroes.css?v=${versions.extra.get("public-heroes.css")}`,
    `/info.css?v=${versions.extra.get("info.css")}`,
    `/script.js?v=${versions.script}`,
    `/shared/app/app.js?v=${versions.app}`,
    `/shared/app/scroll-restoration-boot.js?v=${versions.scrollRestorationBoot}`,
    `/shared/archive-record.js?v=${versions.archiveRecord}`,
    `/shared/archive-search.js?v=${versions.archiveSearch}`,
    ...offlineAppModuleUrls,
  ]);

  return [...precacheUrls].sort();
}

function renderServiceWorker({ versions, manifest }) {
  const precacheUrls = createPrecacheUrlSet(manifest, versions);
  const cacheVersion = hashBuffer(
    Buffer.from(
      JSON.stringify({
        script: versions.script,
        app: versions.app,
        scrollRestorationBoot: versions.scrollRestorationBoot,
        style: versions.style,
        publicHeroes: versions.extra.get("public-heroes.css"),
        info: versions.extra.get("info.css"),
        archiveRecord: versions.archiveRecord,
        archiveSearch: versions.archiveSearch,
        icons: versions.icons,
        precacheUrls,
      }),
    ),
  );

  return [
    GENERATED_JS_BANNER,
    `const CACHE_VERSION = "${cacheVersion}";`,
    'const HTML_CACHE = `echo-archives-html-${CACHE_VERSION}`;',
    'const ASSET_CACHE = `echo-archives-assets-${CACHE_VERSION}`;',
    `const PRECACHE_URLS = ${JSON.stringify(precacheUrls, null, 2)};`,
    'const OFFLINE_FALLBACK_URL = "/offline.html";',
    "",
    "self.addEventListener(\"install\", (event) => {",
    "  event.waitUntil(",
    "    caches.open(ASSET_CACHE).then((cache) => cache.addAll(PRECACHE_URLS)).then(() => self.skipWaiting()),",
    "  );",
    "});",
    "",
    "self.addEventListener(\"activate\", (event) => {",
    "  event.waitUntil(",
    "    caches",
    "      .keys()",
    "      .then((keys) => Promise.all(keys.filter((key) => key.startsWith(\"echo-archives-\") && key !== HTML_CACHE && key !== ASSET_CACHE).map((key) => caches.delete(key))))",
    "      .then(async () => {",
    "        const clients = await self.clients.matchAll({ type: \"window\", includeUncontrolled: true });",
    "        await Promise.all(clients.map((client) => cacheVisitedPage(client.url)));",
    "        await self.clients.claim();",
    "      }),",
    "  );",
    "});",
    "",
    "self.addEventListener(\"fetch\", (event) => {",
    "  const { request } = event;",
    "  if (request.method !== \"GET\") {",
    "    return;",
    "  }",
    "",
    "  const url = new URL(request.url);",
    "  if (url.origin !== self.location.origin || url.pathname.startsWith(\"/api/\")) {",
    "    return;",
    "  }",
    "",
    "  if (request.mode === \"navigate\") {",
    "    event.respondWith(handleNavigationRequest(request));",
    "    return;",
    "  }",
    "",
    "  event.respondWith(handleAssetRequest(request));",
    "});",
    "",
    "self.addEventListener(\"message\", (event) => {",
    "  if (event.data?.type !== \"CACHE_VISITED_RESOURCES\") {",
    "    return;",
    "  }",
    "",
    "  const responsePort = event.ports?.[0];",
    "  event.waitUntil(",
    "    cacheVisitedResources(event.data.urls)",
    "      .then((cached) => responsePort?.postMessage({ cached }))",
    "      .catch(() => responsePort?.postMessage({ cached: 0 })),",
    "  );",
    "});",
    "",
    "async function handleNavigationRequest(request) {",
    "  const cache = await caches.open(HTML_CACHE);",
    "",
    "  try {",
    "    const response = await fetch(request);",
    "    if (response && response.ok) {",
    "      void cache.put(request, response.clone());",
    "    }",
    "    return response;",
    "  } catch (_error) {",
    "    const cachedResponse = await cache.match(request);",
    "    if (cachedResponse) {",
    "      return cachedResponse;",
    "    }",
    "",
    "    const precachedFallback = await caches.match(request.url);",
    "    if (precachedFallback) {",
    "      return precachedFallback;",
    "    }",
    "",
    "    return caches.match(OFFLINE_FALLBACK_URL);",
    "  }",
    "}",
    "",
    "async function cacheVisitedPage(url) {",
    "  try {",
    "    const response = await fetch(url, { credentials: \"same-origin\" });",
    "    if (!response || !response.ok) {",
    "      return;",
    "    }",
    "",
    "    const cache = await caches.open(HTML_CACHE);",
    "    await cache.put(url, response.clone());",
    "  } catch (_error) {",
    "    // A visited page can still be cached by its next successful navigation.",
    "  }",
    "}",
    "",
    "async function cacheVisitedResources(urls) {",
    "  const uniqueUrls = [...new Set(Array.isArray(urls) ? urls : [])]",
    "    .map((value) => {",
    "      try {",
    "        return new URL(value, self.location.origin);",
    "      } catch (_error) {",
    "        return null;",
    "      }",
    "    })",
    "    .filter((url) => url && url.origin === self.location.origin && !url.pathname.startsWith(\"/api/\"));",
    "  let cached = 0;",
    "",
    "  await Promise.all(uniqueUrls.map(async (url) => {",
    "    try {",
    "      const response = await fetch(url.href, { credentials: \"same-origin\" });",
    "      if (!response || !response.ok) {",
    "        return;",
    "      }",
    "      const destinationCache = isHtmlUrl(url) ? HTML_CACHE : ASSET_CACHE;",
    "      const cache = await caches.open(destinationCache);",
    "      await cache.put(url.href, response.clone());",
    "      cached += 1;",
    "    } catch (_error) {",
    "      // Individual optional assets must not prevent the visited page from becoming offline-ready.",
    "    }",
    "  }));",
    "  return cached;",
    "}",
    "",
    "function isHtmlUrl(url) {",
    "  return url.pathname === \"/\" || url.pathname.endsWith(\"/\") || url.pathname.endsWith(\".html\") || !/\\.[a-z0-9]+$/i.test(url.pathname);",
    "}",
    "",
    "async function handleAssetRequest(request) {",
    "  const url = new URL(request.url);",
    "  if (shouldUseNetworkFirstAssetStrategy(request, url)) {",
    "    return handleNetworkFirstAssetRequest(request);",
    "  }",
    "",
    "  const cachedResponse = await caches.match(request);",
    "  if (cachedResponse) {",
    "    void refreshAssetCache(request);",
    "    return cachedResponse;",
    "  }",
    "",
    "  const response = await fetch(request);",
    "  if (response && response.ok) {",
    "    const cache = await caches.open(ASSET_CACHE);",
    "    void cache.put(request, response.clone());",
    "  }",
    "",
    "  return response;",
    "}",
    "",
    "function shouldUseNetworkFirstAssetStrategy(request, url) {",
    "  return request.destination === \"script\" || request.destination === \"style\" || /\\.(?:js|css)$/i.test(url.pathname);",
    "}",
    "",
    "async function handleNetworkFirstAssetRequest(request) {",
    "  try {",
    "    const response = await fetch(request);",
    "    if (response && response.ok) {",
    "      const cache = await caches.open(ASSET_CACHE);",
    "      void cache.put(request, response.clone());",
    "    }",
    "",
    "    return response;",
    "  } catch (_error) {",
    "    const cachedResponse = await caches.match(request);",
    "    if (cachedResponse) {",
    "      return cachedResponse;",
    "    }",
    "",
    "    throw _error;",
    "  }",
    "}",
    "",
    "async function refreshAssetCache(request) {",
    "  const cachedResponse = await caches.match(request);",
    "  try {",
    "    const response = await fetch(request);",
    "    if (!response || !response.ok) {",
    "      return;",
    "    }",
    "",
    "    const cache = await caches.open(ASSET_CACHE);",
    "    await cache.put(request, response.clone());",
    "  } catch (_error) {",
    "    // Keep the cached asset when refresh fails.",
    "  }",
    "}",
    "",
  ].join("\n");
}

function writeStaticSitemap({ siteUrl, catalog, collections }) {
  const sitemapXml = buildSitemapXml({ siteUrl, catalog, collections });
  writeFile(path.join(ROOT, "sitemap.xml"), `${sitemapXml}\n`);
}

function writeRobots({ siteUrl }) {
  const contents = [
    "User-agent: *",
    "Allow: /",
    "Disallow: /api/",
    "Disallow: /maintainer/",
    "",
    `Sitemap: ${new URL("/sitemap.xml", `${siteUrl}/`).toString()}`,
    "",
  ].join("\n");
  writeFile(path.join(ROOT, "robots.txt"), contents);
}

async function loadHomeConfig() {
  const homeConfigModuleUrl = pathToFileURL(path.join(ROOT, "shared", "app", "home-config.js")).href;
  const homeConfigModule = await import(homeConfigModuleUrl);
  return {
    homeMostPopularIds: Array.isArray(homeConfigModule.HOME_MOST_POPULAR_IDS) ? homeConfigModule.HOME_MOST_POPULAR_IDS : [],
    homeFavoriteRouteIds: Array.isArray(homeConfigModule.HOME_FAVORITE_ROUTE_IDS) ? homeConfigModule.HOME_FAVORITE_ROUTE_IDS : [],
  };
}

async function loadSubmitPrerender(archivistEnabled) {
  const moduleUrl = (relativePath) => pathToFileURL(path.join(ROOT, relativePath)).href;
  const [configModule, renderModule, stateModule, utilsModule] = await Promise.all([
    import(moduleUrl("shared/app/submit/config.js")),
    import(moduleUrl("shared/app/submit/render.js")),
    import(moduleUrl("shared/app/submit/state.js")),
    import(moduleUrl("shared/app/submit/utils.js")),
  ]);
  const config = configModule.MODE_CONFIG.show;
  const draft = stateModule.createDrafts().show;
  const context = {
    tagFieldOptions: { selectedTags: configModule.FALLBACK_TAG_OPTIONS },
    activeTagField: "",
    tagPickerOpen: false,
    tagQuery: "",
    tagHighlightIndex: -1,
    selectedShow: null,
    searchResults: [],
    searchOpen: false,
    lookupStatus: "idle",
    lookupMessage: "The show list loads when this form needs it.",
    showHighlightIndex: -1,
    showContext: null,
    showContextStatus: "idle",
    showContextMessage: "",
  };

  return {
    submitModeCards: renderModule.renderModeCardsMarkup("show"),
    submitFormIntro: `
      <div class="submit-form-intro-meta">
        <span class="submit-form-icon" aria-hidden="true">${utilsModule.iconMarkup(config.introIcon)}</span>
        <h2>${utilsModule.escapeHtml(config.introTitle)}</h2>
      </div>
      <p>${utilsModule.escapeHtml(config.introDescription)}</p>
    `,
    submitDynamicFields: renderModule.renderModeFields("show", draft, context),
    submitSideRail: config.railCards
      .map((card) => renderModule.renderRailCard(card, { archivistEnabled }))
      .join(""),
    submitFooterNote: utilsModule.escapeHtml(config.footerNote),
  };
}

async function main() {
  await generateStaticImageVariants(ROOT);
  buildEntryAssets();

  const cssVersions = new Map(
    Object.keys(ENTRY_ASSETS)
      .filter((fileName) => fileName.endsWith(".css"))
      .map((fileName) => [fileName, hashFile(fileName)]),
  );

  const versions = {
    app: hashTree("shared/app"),
    scrollRestorationBoot: hashFile("shared/app/scroll-restoration-boot.js"),
    archiveRecord: hashFile("shared/archive-record.js"),
    archiveSearch: hashFile("shared/archive-search.js"),
    shows: hashFile("data/shows.json"),
    collections: hashFile("data/collections.json"),
    searchIndex: hashFile("data/search-index.json"),
    icons: ["favicon.ico", "apple-touch-icon.png", "icon-192.png", "icon-512.png"].map(hashFile),
    script: hashFile("script.js"),
    style: cssVersions.get("style.css"),
    home: cssVersions.get("home.css"),
    extra: new Map([...cssVersions].filter(([fileName]) => !["style.css", "home.css"].includes(fileName))),
  };
  const sourceManifest = JSON.parse(readFile(MANIFEST_PATH));
  const siteUrl = resolveSiteUrl(sourceManifest);
  const manifest = resolveManifestCanonicalUrls(sourceManifest, siteUrl);
  const catalog = readJsonIfExists(path.join(ROOT, "data", "shows.json"), []);
  const collections = readJsonIfExists(path.join(ROOT, "data", "collections.json"), []);
  const archiveStats = readJsonIfExists(path.join(ROOT, "data", "archive-stats.json"), {});
  const seoContext = { siteUrl, catalog, collections, archiveStats };
  const homeConfig = await loadHomeConfig();
  const submitPrerender = await loadSubmitPrerender(parseBoolean(process.env.ARCHIVIST_ENABLED, false));
  const socialLinks = JSON.parse(readFile(SOCIAL_LINKS_PATH));
  const partials = {
    head: readFile(path.join(PARTIALS_DIR, "head.html")).trim(),
    header: readFile(path.join(PARTIALS_DIR, "header.html")).trim(),
    floatingControls: readFile(path.join(PARTIALS_DIR, "floating-controls.html")).trim(),
    footer: renderTemplate(readFile(path.join(PARTIALS_DIR, "footer.html")).trim(), {
      socialLinks: renderSocialLinks(socialLinks),
    }),
  };

  writeFile(path.join(ROOT, "sw.js"), renderServiceWorker({ versions, manifest }));
  writeStaticSitemap({ siteUrl, catalog, collections });
  writeRobots({ siteUrl });

  manifest.forEach((entry) => {
    const outputPath = path.join(ROOT, entry.output);
    const pageMarkup = renderPage(entry, partials, versions, homeConfig, seoContext, submitPrerender);
    writeFile(outputPath, pageMarkup);

    const cleanRouteAlias = resolveCleanRouteAlias(entry);
    if (cleanRouteAlias) {
      const aliasMarkup = shouldNoIndexAlias(cleanRouteAlias)
        ? renderPage({ ...entry, noIndex: true }, partials, versions, homeConfig, seoContext, submitPrerender)
        : pageMarkup;
      writeFile(path.join(ROOT, cleanRouteAlias, "index.html"), aliasMarkup);
    }
  });
}

if (require.main === module) {
  main().catch((error) => {
    console.error(error);
    process.exitCode = 1;
  });
}

module.exports = {
  createPrecacheUrlSet,
  resolveManifestCanonicalUrls,
  resolveSiteUrl,
  serializeStructuredData,
};
