const crypto = require("node:crypto");
const fs = require("node:fs");
const path = require("node:path");

const { buildSitemapXml } = require("../backend/lib/sitemap");

const ROOT = path.resolve(__dirname, "..");
const SITE_SRC = path.join(ROOT, "site-src");
const PARTIALS_DIR = path.join(SITE_SRC, "partials");
const PAGES_DIR = path.join(SITE_SRC, "pages");
const MANIFEST_PATH = path.join(SITE_SRC, "page-manifest.json");
const GENERATED_PAGE_BANNER = "<!-- Generated from site-src by tools/build-pages.js. Do not edit this file directly. -->";
const GENERATED_JS_BANNER = "// Generated from tools/build-pages.js. Do not edit this file directly.";
const GENERATED_CSS_BANNER = "/* Generated from tools/build-pages.js. Do not edit this file directly. */";
const DEFAULT_PLAUSIBLE_SCRIPT_SRC = "https://plausible.io/js/script.js";
const NOINDEX_ALIAS_PATHS = new Set(["show", "collection"]);

const ENTRY_ASSETS = {
  "script.js": ({ appVersion }) => [
    GENERATED_JS_BANNER,
    `import { initializeApp } from "./shared/app/app.js?v=${appVersion}";`,
    "",
    "initializeApp().catch((error) => {",
    '  console.error("Failed to initialize the Echo Archives app.", error);',
    "});",
    "",
  ].join("\n"),
  "style.css": ({ baseVersion }) => [
    GENERATED_CSS_BANNER,
    `@import url("shared/styles/base/variables.css?v=${baseVersion}");`,
    `@import url("shared/styles/base/global.css?v=${baseVersion}");`,
    `@import url("shared/styles/base/header-footer.css?v=${baseVersion}");`,
    `@import url("shared/styles/base/chat.css?v=${baseVersion}");`,
    "",
  ].join("\n"),
  "home.css": ({ homeVersion, submitVersion, collectionsVersion, creatorsVersion }) => [
    GENERATED_CSS_BANNER,
    `@import url("shared/styles/home/hero.css?v=${homeVersion}");`,
    `@import url("shared/styles/home/filters.css?v=${homeVersion}");`,
    `@import url("shared/styles/home/cards.css?v=${homeVersion}");`,
    `@import url("shared/styles/home/submit.css?v=${submitVersion}");`,
    `@import url("shared/styles/home/maintainer.css?v=${homeVersion}");`,
    `@import url("shared/styles/home/collections.css?v=${collectionsVersion}");`,
    `@import url("shared/styles/home/creators.css?v=${creatorsVersion}");`,
    `@import url("shared/styles/home/responsive.css?v=${homeVersion}");`,
    "",
  ].join("\n"),
  "detail.css": ({ showVersion }) => [
    GENERATED_CSS_BANNER,
    `@import url("shared/styles/show/hero.css?v=${showVersion}");`,
    `@import url("shared/styles/show/sections.css?v=${showVersion}");`,
    `@import url("shared/styles/show/facts-rail.css?v=${showVersion}");`,
    `@import url("shared/styles/show/community.css?v=${showVersion}");`,
    `@import url("shared/styles/show/responsive.css?v=${showVersion}");`,
    "",
  ].join("\n"),
};

function readFile(filePath) {
  return fs.readFileSync(filePath, "utf8");
}

function writeFile(filePath, contents) {
  fs.mkdirSync(path.dirname(filePath), { recursive: true });
  fs.writeFileSync(filePath, contents);
}

function hashBuffer(buffer) {
  return crypto.createHash("sha1").update(buffer).digest("hex").slice(0, 10);
}

function listFilesDeep(startPath) {
  const results = [];

  if (!fs.existsSync(startPath)) {
    return results;
  }

  function walk(currentPath) {
    fs.readdirSync(currentPath, { withFileTypes: true }).forEach((entry) => {
      const absolutePath = path.join(currentPath, entry.name);
      if (entry.isDirectory()) {
        walk(absolutePath);
        return;
      }

      results.push(absolutePath);
    });
  }

  walk(startPath);
  return results.sort((left, right) => left.localeCompare(right));
}

function hashFile(relativePath) {
  return hashBuffer(fs.readFileSync(path.join(ROOT, relativePath)));
}

function hashTree(relativePath) {
  const files = listFilesDeep(path.join(ROOT, relativePath));
  const hash = crypto.createHash("sha1");

  files.forEach((filePath) => {
    hash.update(path.relative(ROOT, filePath));
    hash.update(fs.readFileSync(filePath));
  });

  return hash.digest("hex").slice(0, 10);
}

function stripQuery(value = "") {
  return String(value || "").split("?", 1)[0];
}

function withVersion(relativePath, version) {
  return `${relativePath}?v=${version}`;
}

function renderTemplate(template, replacements) {
  return template.replace(/\{\{([a-zA-Z0-9]+)\}\}/g, (_match, key) => replacements[key] ?? "");
}

function escapeAttribute(value = "") {
  return String(value)
    .replace(/&/g, "&amp;")
    .replace(/"/g, "&quot;");
}

function escapeRegExp(value = "") {
  return String(value).replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

function parseBoolean(value, fallback = false) {
  if (value === undefined) {
    return fallback;
  }

  return /^(1|true|yes|on)$/i.test(String(value).trim());
}

function renderStylesheets(extraStylesheets = [], versions = {}) {
  return [
    `<link rel="stylesheet" href="/style.css?v=${versions.style}" />`,
    `<link rel="stylesheet" href="/home.css?v=${versions.home}" />`,
    ...extraStylesheets.map((href) => {
      const basePath = stripQuery(href);
      const version = versions.extra.get(basePath) || hashFile(basePath);
      return `<link rel="stylesheet" href="/${withVersion(basePath, version)}" />`;
    }),
  ].join("\n");
}

function renderRobotsMeta(entry) {
  return entry.noIndex ? '<meta name="robots" content="noindex, nofollow" />' : "";
}

function renderAnalyticsScript(entry) {
  const plausibleDomain = String(process.env.PLAUSIBLE_DOMAIN || "").trim();
  if (!plausibleDomain || entry.includeAnalytics === false) {
    return "";
  }

  const plausibleScriptSrc = String(process.env.PLAUSIBLE_SCRIPT_SRC || DEFAULT_PLAUSIBLE_SCRIPT_SRC).trim();
  if (!plausibleScriptSrc) {
    return "";
  }

  return `<script defer data-domain="${escapeAttribute(plausibleDomain)}" src="${escapeAttribute(plausibleScriptSrc)}"></script>`;
}

function renderNavLinks(activeNav) {
  const navItems = [
    { id: "browse", label: "Browse", href: "/" },
    { id: "collections", label: "Collections", href: "/collections" },
    { id: "about", label: "About", href: "/about" },
    { id: "submit", label: "Submit", href: "/submit" },
    { id: "for-creators", label: "For creators", href: "/for-creators" },
  ];

  return navItems
    .map((item) => {
      const activeClass = item.id === activeNav ? ' class="is-active"' : "";
      return `<a${activeClass} href="${item.href}">${item.label}</a>`;
    })
    .join("\n    ");
}

function resolveMainContentTarget(entry) {
  return entry.source === "show.html" ? "showRoot" : "main-content";
}

function renderSkipLink(targetId) {
  return `<a class="skip-link" href="#${escapeAttribute(targetId)}">Skip to main content</a>`;
}

function ensureMainContentTarget(pageBody, targetId) {
  if (!targetId) {
    return pageBody;
  }

  const existingTargetPattern = new RegExp(`<main\\b([^>]*\\bid="${escapeRegExp(targetId)}"[^>]*)>`, "i");
  if (existingTargetPattern.test(pageBody)) {
    return pageBody.replace(existingTargetPattern, (match, attributes) => {
      if (/\btabindex=/.test(attributes)) {
        return match;
      }

      return `<main${attributes} tabindex="-1">`;
    });
  }

  return pageBody.replace(/<main\b(?![^>]*\bid=)/i, `<main id="${escapeAttribute(targetId)}" tabindex="-1"`);
}

function renderPageBody(entry) {
  const creatorSpotlightEnabled = parseBoolean(process.env.CREATOR_SPOTLIGHT_PREVIEW_ENABLED, true);
  const pageBody = ensureMainContentTarget(readFile(path.join(PAGES_DIR, entry.source)).trim(), resolveMainContentTarget(entry));

  return renderTemplate(pageBody, {
    creatorSpotlightVisibilityAttribute:
      entry.source === "for-creators.html" && !creatorSpotlightEnabled ? " hidden" : "",
  });
}

function buildEntryAssets() {
  const nestedVersions = {
    appVersion: hashTree("shared/app"),
    baseVersion: hashTree("shared/styles/base"),
    homeVersion: hashTree("shared/styles/home"),
    submitVersion: hashTree("shared/styles/home/submit"),
    collectionsVersion: hashTree("shared/styles/home/collections"),
    creatorsVersion: hashTree("shared/styles/home/creators"),
    showVersion: hashTree("shared/styles/show"),
  };

  Object.entries(ENTRY_ASSETS).forEach(([fileName, render]) => {
    writeFile(path.join(ROOT, fileName), render(nestedVersions));
  });
}

function renderPage(entry, partials, versions) {
  const homeCardHoverExpandEnabled = parseBoolean(process.env.HOME_CARD_HOVER_EXPAND_ENABLED, false);
  const headMarkup = renderTemplate(partials.head, {
    title: entry.title,
    description: entry.description,
    canonicalUrl: entry.canonicalUrl,
    robotsMeta: renderRobotsMeta(entry),
    analyticsScript: renderAnalyticsScript(entry),
    stylesheets: renderStylesheets(entry.extraStylesheets, versions),
  });
  const headerMarkup = renderTemplate(partials.header, {
    navLinks: renderNavLinks(entry.activeNav),
  });
  const mainContentTarget = resolveMainContentTarget(entry);
  const pageBody = renderPageBody(entry);
  const bodySections = [
    renderSkipLink(mainContentTarget),
    headerMarkup,
    entry.includeChatShell ? partials.chatShell : "",
    pageBody,
    entry.includeFloatingControls ? partials.floatingControls : "",
    partials.footer,
    `  <script src="/shared/archive-record.js?v=${versions.archiveRecord}"></script>`,
    `  <script src="/shared/archive-search.js?v=${versions.archiveSearch}"></script>`,
    `  <script type="module" src="/script.js?v=${versions.script}"></script>`,
  ]
    .filter(Boolean)
    .join("\n\n");

  return [
    "<!DOCTYPE html>",
    GENERATED_PAGE_BANNER,
    '<html lang="en">',
    "<head>",
    headMarkup,
    "</head>",
    `<body class="${entry.bodyClass}" data-home-card-hover-expand-enabled="${String(homeCardHoverExpandEnabled)}">`,
    bodySections,
    "</body>",
    "</html>",
    "",
  ].join("\n");
}

function readJsonIfExists(filePath, fallbackValue) {
  try {
    return JSON.parse(readFile(filePath));
  } catch (_error) {
    return fallbackValue;
  }
}

function resolveCleanRouteAlias(entry) {
  if (!entry?.canonicalUrl) {
    return null;
  }

  let pathname = "";
  try {
    pathname = new URL(entry.canonicalUrl).pathname || "";
  } catch (_error) {
    return null;
  }

  if (!pathname || pathname === "/" || pathname.endsWith(".html")) {
    return null;
  }

  return pathname.replace(/^\/+/, "");
}

function shouldNoIndexAlias(cleanRouteAlias) {
  return NOINDEX_ALIAS_PATHS.has(cleanRouteAlias);
}

function resolveSiteUrl(manifest) {
  const configured = String(process.env.SITE_URL || "").trim();
  if (configured) {
    return configured;
  }

  const homeEntry = Array.isArray(manifest) ? manifest.find((entry) => entry.output === "index.html") : null;
  if (!homeEntry?.canonicalUrl) {
    return "https://echo.continental-hub.com";
  }

  try {
    return new URL(homeEntry.canonicalUrl).origin;
  } catch (_error) {
    return "https://echo.continental-hub.com";
  }
}

function createPrecacheUrlSet(manifest, versions) {
  const precacheUrls = new Set([
    "/",
    "/404.html",
    "/500.html",
    "/offline.html",
    "/site.webmanifest",
    "/favicon.ico",
    "/apple-touch-icon.png",
    "/icon-192.png",
    "/icon-512.png",
    "/og-image.png",
    `/style.css?v=${versions.style}`,
    `/home.css?v=${versions.home}`,
    `/detail.css?v=${versions.extra.get("detail.css")}`,
    `/script.js?v=${versions.script}`,
    `/shared/archive-record.js?v=${versions.archiveRecord}`,
    `/shared/archive-search.js?v=${versions.archiveSearch}`,
    "/data/shows.json",
    "/data/collections.json",
    "/data/search-index.json",
  ]);

  manifest.forEach((entry) => {
    if (entry.output.startsWith("maintainer/") || entry.output === "offline.html") {
      return;
    }

    try {
      const canonicalPath = new URL(entry.canonicalUrl).pathname || "";
      if (canonicalPath && !["/collection", "/show"].includes(canonicalPath)) {
        precacheUrls.add(canonicalPath);
      }
    } catch (_error) {
      // Ignore malformed canonical URLs here; the page build still owns correctness.
    }
  });

  return [...precacheUrls].sort();
}

function renderServiceWorker({ versions, manifest }) {
  const precacheUrls = createPrecacheUrlSet(manifest, versions);
  const cacheVersion = hashBuffer(
    Buffer.from(
      JSON.stringify({
        script: versions.script,
        style: versions.style,
        home: versions.home,
        detail: versions.extra.get("detail.css"),
        archiveRecord: versions.archiveRecord,
        archiveSearch: versions.archiveSearch,
        precacheUrls,
      }),
    ),
  );

  return [
    GENERATED_JS_BANNER,
    `const CACHE_VERSION = "${cacheVersion}";`,
    'const HTML_CACHE = `echo-archives-html-${CACHE_VERSION}`;',
    'const ASSET_CACHE = `echo-archives-assets-${CACHE_VERSION}`;',
    `const PRECACHE_URLS = ${JSON.stringify(precacheUrls, null, 2)};`,
    'const OFFLINE_FALLBACK_URL = "/offline.html";',
    "",
    "self.addEventListener(\"install\", (event) => {",
    "  event.waitUntil(",
    "    caches.open(ASSET_CACHE).then((cache) => cache.addAll(PRECACHE_URLS)).then(() => self.skipWaiting()),",
    "  );",
    "});",
    "",
    "self.addEventListener(\"activate\", (event) => {",
    "  event.waitUntil(",
    "    caches",
    "      .keys()",
    "      .then((keys) => Promise.all(keys.filter((key) => key.startsWith(\"echo-archives-\") && key !== HTML_CACHE && key !== ASSET_CACHE).map((key) => caches.delete(key))))",
    "      .then(() => self.clients.claim()),",
    "  );",
    "});",
    "",
    "self.addEventListener(\"fetch\", (event) => {",
    "  const { request } = event;",
    "  if (request.method !== \"GET\") {",
    "    return;",
    "  }",
    "",
    "  const url = new URL(request.url);",
    "  if (url.origin !== self.location.origin || url.pathname.startsWith(\"/api/\")) {",
    "    return;",
    "  }",
    "",
    "  if (request.mode === \"navigate\") {",
    "    event.respondWith(handleNavigationRequest(request));",
    "    return;",
    "  }",
    "",
    "  event.respondWith(handleAssetRequest(request));",
    "});",
    "",
    "async function handleNavigationRequest(request) {",
    "  const cache = await caches.open(HTML_CACHE);",
    "",
    "  try {",
    "    const response = await fetch(request);",
    "    if (response && response.ok) {",
    "      void cache.put(request, response.clone());",
    "    }",
    "    return response;",
    "  } catch (_error) {",
    "    const cachedResponse = await cache.match(request);",
    "    if (cachedResponse) {",
    "      return cachedResponse;",
    "    }",
    "",
    "    const precachedFallback = await caches.match(request.url);",
    "    if (precachedFallback) {",
    "      return precachedFallback;",
    "    }",
    "",
    "    return caches.match(OFFLINE_FALLBACK_URL);",
    "  }",
    "}",
    "",
    "async function handleAssetRequest(request) {",
    "  const cachedResponse = await caches.match(request);",
    "  if (cachedResponse) {",
    "    void refreshAssetCache(request);",
    "    return cachedResponse;",
    "  }",
    "",
    "  const response = await fetch(request);",
    "  if (response && response.ok) {",
    "    const cache = await caches.open(ASSET_CACHE);",
    "    void cache.put(request, response.clone());",
    "  }",
    "",
    "  return response;",
    "}",
    "",
    "async function refreshAssetCache(request) {",
    "  try {",
    "    const response = await fetch(request);",
    "    if (!response || !response.ok) {",
    "      return;",
    "    }",
    "",
    "    const cache = await caches.open(ASSET_CACHE);",
    "    await cache.put(request, response.clone());",
    "  } catch (_error) {",
    "    // Keep the cached asset when refresh fails.",
    "  }",
    "}",
    "",
  ].join("\n");
}

function writeStaticSitemap({ manifest }) {
  const siteUrl = resolveSiteUrl(manifest);
  const catalog = readJsonIfExists(path.join(ROOT, "data", "shows.json"), []);
  const collections = readJsonIfExists(path.join(ROOT, "data", "collections.json"), []);
  const sitemapXml = buildSitemapXml({ siteUrl, catalog, collections });
  writeFile(path.join(ROOT, "sitemap.xml"), `${sitemapXml}\n`);
}

function main() {
  buildEntryAssets();

  const versions = {
    archiveRecord: hashFile("shared/archive-record.js"),
    archiveSearch: hashFile("shared/archive-search.js"),
    script: hashFile("script.js"),
    style: hashFile("style.css"),
    home: hashFile("home.css"),
    extra: new Map([
      ["detail.css", hashFile("detail.css")],
    ]),
  };
  const manifest = JSON.parse(readFile(MANIFEST_PATH));
  const partials = {
    head: readFile(path.join(PARTIALS_DIR, "head.html")).trim(),
    header: readFile(path.join(PARTIALS_DIR, "header.html")).trim(),
    chatShell: readFile(path.join(PARTIALS_DIR, "chat-shell.html")).trim(),
    floatingControls: readFile(path.join(PARTIALS_DIR, "floating-controls.html")).trim(),
    footer: readFile(path.join(PARTIALS_DIR, "footer.html")).trim(),
  };

  writeFile(path.join(ROOT, "sw.js"), renderServiceWorker({ versions, manifest }));
  writeStaticSitemap({ manifest });

  manifest.forEach((entry) => {
    const outputPath = path.join(ROOT, entry.output);
    const pageMarkup = renderPage(entry, partials, versions);
    writeFile(outputPath, pageMarkup);

    const cleanRouteAlias = resolveCleanRouteAlias(entry);
    if (cleanRouteAlias) {
      const aliasMarkup = shouldNoIndexAlias(cleanRouteAlias)
        ? renderPage({ ...entry, noIndex: true }, partials, versions)
        : pageMarkup;
      writeFile(path.join(ROOT, cleanRouteAlias, "index.html"), aliasMarkup);
    }
  });
}

main();
